
const biology = [
    {
    year: "2021",
    list: [
      {
        title: "Elgadal, A. H., & Mariod, A. A.",
        subtitle: "“Item Analysis of Multiple-choice Questions (MCQs): Assessment Tool For Quality Assurance Measures. ” ",
        italic: "Sudan Journal of Medical Sciences (SJMS), 16(3) ",
        pp: " (2021).",
        url: ". https://doi.org/10.18502/sjms.v16i3.9695",
      },
      {
        title: "Suzy Munir Salama, Hammad Ali Fadlalmola, Manal Mohammed Abdel Hafeez, Samia Ali Mohamed Ahmed, Rafiah Awad Mohamed, Nora Mohammed Ali Elatta, and Abdalbasit Adam Mariod. ",
        subtitle: "“Effectiveness of Gum Arabic in Diabetes and its Complications: A Narrative Review” ",
        italic: "Sudan Journal of Medical Sciences, 16, (3): 436–453. ",
        pp: "DOI 10.18502/sjms.v16i3.9703, (2021).",
        url: "#",
      },
      {
        title: "Amira .Y. Boshra, Fatima.A.Ali Massad, Eshraga .M.Abdalrhman, Sabah.M.Abbas, Amel.A.Hassan, Manal.M.Mahamedan, Abdalbasit A. Mariod, Nora .M.A.Elatta, Huda .Kh.A.Masaad, Amal.M.Hamid . ",
        subtitle: "“Composition, hydrology and health benefits of Zamzam water: mini-review. Bionatura“ ",
        italic: "#",
        pp: " (2021).",
        url: "#",
      },
      {
        title: "Salaheldeen, M., Mariod, A.A., Aroua, M.K., Rahman, S.M.A., Soudagar, M.E.M., Fattah, I.M.R.  ",
        subtitle: "“ Current State and Perspectives on Transesterification of Triglycerides for Biodiesel Production.”  ",
        italic: "",
        pp: "Catalysts 2021, 11, 1121, (2021) ",
        url: "https://doi.org/10.3390/catal11091121",
      },
      {
        title: "Althagafi AM, Alshegifi HM, Qussyier TS, Tobaiqy M, Mariod A. ",
        subtitle: "“Mycotoxin-contaminated food and feed in Saudi Arabia: review of occurrence and toxicity. “",
        italic: "Foods and Raw Materials 9(1):174–183. ",
        pp: ",  (2021).",
        url: "#",
      },
      {
        title: "Yahia A., Mariod A. ",
        subtitle: "“Effect of health education about personal hygiene on student’s health in primary school.”",
        italic: " Journal of International Health Sciences and Management, 7(13):83-89, ",
        pp: " (2021) ",
        url: "#",
      },
      {
        title: "Mariod, A., Abdalrahman, E., Shakak, M. ",
        subtitle: "“'Impact of incorporation of Monechma ciliatum seed flour on the chemical composition,” ",
        italic: "nutritional value and sensory evaluation of sorghum Kisra. Egyptian Journal of Food Science, 49, (1):97-106 doi: 10.21608/ejfs.2021.45938.1082. ",
        pp: " (2021).  ",
        url: "#",
      },
      {
        title: "Adam Abdelmalik, M. A., Mariod, A. A., Beraima, M. A., Fadlalmola, H. A., Rahama, E. E. S., Masaad, H. K., Osman Ahmed, M. I., Ibrahim Abbakr, I. A., Abdelraheem Osman, E. G., & Ibrahim Hassan, I. M.",
        subtitle: " “Knowledge and Practice Regarding Coronavirus Disease Prevention (COVID-19) Among Internally Displaced Persons in Camps in Central Darfur Region, Sudan. ” ",
        italic: "Sudan Journal of Medical Sciences (SJMS), 16(2), 178–195. ",
        pp: "(2021). ",
        url: "https://doi.org/10.18502/sjms.v16i2.9287 ",
      },
      {
        title: "Mariod, A.A., Tyfoor, A.A. & Turki, I.Y. ",
        subtitle: "“Watermelon bug (Aspongopus viduatus) full‐fat meals as an alternative dietary protein on broiler chickens’ growth performance, meat, and blood. ” ",
        italic: "Int J Trop Insect Sci. ",
        pp: ", (2021)",
        url: "https://doi.org/10.1007/s42690-021-00482-y",
      },
      {
        title: "Ahmed, H., A. Mariod, and T. A. A. Hammoda. ",
        subtitle: "“The Chronic Toxicity Studies of Camellia Seed Oil Containing Tea Saponins on Mice Blood and Organs” ",
        italic: "International Journal of Life Sciences and Biotechnology, 4(2): 159- 173. DOI: 10.38001/ijlsb.807980. ",
        pp: ", (2021).",
        url: "#",
      },
      {
        title: "Abdalbasit Adam MARIOD, Makarim Mutasim Mohamed MUSTAFA, Abdelazim Ahmed Mohamed, NOUR, Mahmood Ameen ABDALLA, Suzy Munir SALAMA, Nahla Saeed Al WAJEEH. ",
        subtitle: "”Antioxidant activity and acute toxicity of two Lagenaria siceraria (Molina) Standl.” ",
        italic: "Sudan. Acta agriculturae Slovenica, 116/2, 261–271. ",
        pp: " (2021).",
        url: "#",
      },
      {
        title: "Hoda Elsayed Mohammed & Sama Mohammed N. Attiyah. ",
        subtitle: "“Prognostic Significance Association of Neutrophil-To- Lymphocyte Ratio and Platelets- To-Lymphocyte Ratio with Mortality in COVID19 Patients ” ",
        italic: "Indian Journal of Forensic Medicine & Toxicology, 15(4), 3372-3381.",
        pp: " (2021) ",
        url: "https://medicopublication.com/index.php/ijfmt/article/view/17354",
      },
      {
        title: "Attiyah, S. M. and Mohammed, H. E. . ",
        subtitle: "”Effectiveness of Turmeric and Extra Virgin Olive Oil in the Management of IL 6 and IL 10 in Healthy Mice ” ",
        italic: "Journal of Pharmaceutical Research International,  ",
        pp: "33(39A), pp. 9-16. DOI: 10.9734/jpri/2021/v33i39A32134",
        url: "#",
      },
	  {
        title: "Hoda Elsayed Mohammed, Sama Mohammed Attiyah, Shimaa Attia Atta, ",
        subtitle: "“Comparative Study on the Pro-Inflammatory Activity of Turmeric (Curcuma longa) and flaxseed (Linumusitatissimum). “",
        italic: " Annals of the Romanian Society for Cell Biology, 6329–6335, ",
        pp: " (2021)",
        url: "https://www.annalsofrscb.ro/index.php/journal/article/view/3224",
      },
	  {
        title: " Hoda M Elsayed, ",
        subtitle: "“The Bioactive Effect Of Royal Jelly Against Histamine Level Induced By Lysophospha-tidic Acid (LPA). “",
        italic: " Nat. Volatiles & Essent. Oils, ",
        pp: "2021; 8(4): 11675-11684",
        url: "#",
      },
      ]
    },
    {
    year: "2020",
    list: [
      {
        title: "Marıod, A., Idrıs, ",
        subtitle: "“Revelation and determination of 3-monochloropropane-1,2-DIOL (3-MCPD) in bread from modern bakeries in Khartoum state, “",
        italic: " Sudan. Eurasian Journal of Food Science and Technology, 4(2):70-81, ",
        pp: " (2020)",
        url: "#",
      },
      {
        title: "Amal Mohamed Elhusein Salih, Hawaa Mohamed Hassan Abd Allah, Abdalbasit A. Mariod, Hammad Ali Fadlalmola, Altyeb AbdElazim, ",
        subtitle: "“Nurses Performance Regarding Non Pharmaceutical Pain Management.”, ",
        italic: "Pak Euro Journal of Medical and Life Sciences. ",
        pp: ".  3, ( 4): 176-186, (2020)",
        url: "#",
      },
      {
        title: "Abdalbasit Adam Mariod, Noha Fadle, Hiba Abdel Rahman Ali, Alfatih Ahmed Hassan,",
        subtitle: "” Antioxidant activity, total phenolic compounds and LD50 bioassay (toxicity) activity of the fermented wood “Nikhra” fractions of combretum hartmannianum, terminalia laxiflora and acacia seyal.”, ",
        italic: "Int J Agric For Life Sci 4(2): 298-302. ",
        pp: " (2020).",
        url: "#",
      },
      {
        title: "Elrasheid Tahir, H., G. Komla Mahunu, M. Arslan, L. Zhihua, Z. Wen, Z. Xiaobo, A. Adam Mariod and S. Jiyong,",
        subtitle: "” Feasibility study for the use of colorimetric sensor arrays, NIR and FT-IR spectroscopy in the quantitative analysis of volatile components in honey.”, ",
        italic: "Microchemical Journal: 105730. doi.org/10.1016/j.microc.2020.105730. ",
        pp: " (2020).",
        url: "#",
      },
      {
        title: "Mohammed Cheurfa, Rachida Allem, Khawla Zabel, Waffa Aichouni, and Abdalbasit Mariod, ",
        subtitle: "“A comparative study on solvent extraction effect on the phytochemical profiling and antioxidant capacity of Zizyphus lotus L and Glycyrrhizaglabra L roots” ",
        italic: "Int J Agric For Life Sci ",
        pp: "(2020) 4(2): 167-172.",
        url: "#",
      },
      {
        title: "Marıod, A, ",
        subtitle: "” Short communication: Proximate chemical and nutritional composition of Moringa oleifera, and Adansonia digitata leaves” ",
        italic: "Eurasian Journal of Food Science and Technology,4(1):34-40. ",
        pp: " (2020).",
        url: "https://dergipark.org.tr/en/pub/ejfst/issue/56793/727013",
      },
      {
        title: "Mohammed Cheurfa, Mohamed Achouche, Ahmed Azouzi, Abdalbasit Mariod,",
        subtitle: "” Antioxidant and anti-diabetic activity of pomegranate (Punica granatum L.) leaves extracts”",
        italic: " Foods and Raw Materials, ",
        pp: " (2020). DOI: 10.21603/2308-4057-2020-2-329-336",
        url: "#",
      },
      {
        title: "Abdalbasit Adam Mariod  and Suzy Munir Salama,",
        subtitle: "” The Efficacy of Processing Strategies on the Gastroprotective Potentiality of Chenopodium quinoa Seeds” ",
        italic: "The Scientific World Journal. ",
        pp: "2020-05-28 Volume 2020, Article ID 6326452, 16 pages ",
        url: "https://doi.org/10.1155/2020/6326452",
      },
      {
        title: "Ali, AMA., Albashir, WAM., Mariod,",
        subtitle: "” Nursing Documentation in Selected Hospitals in Khartoum State-Sudan.” ",
        italic: "Journal of International Health Sciences and Management, ",
        pp: "6(10): 108-120 (2020).",
        url: "#",
      },
      {
        title: "Abdalbasit Adam Mariod, Manal Abasher Ahmed, Ismail Hassan Hussein and Bertrand Matthaus ",
        subtitle: "” Chemical composition, fatty acids and oil stability of chrozophora brochiana (vis.) Schweinf. Seed as affectedby germination process.”",
        italic: "Bangladesh Journal of Botany,",
        pp: "49(1): 1-11).",
        url: "#",
      },
	  {
        title: "Haroon Elrasheid Tahir, Muhammad Arslan,  Gustav Komla Mahunu,  Abdalbasit Adam Mariod, Zhang Wen,  Zou Xiaobo,  Huang Xiaowei, Shi Jiyong, Hesham El-Seedi ",
        subtitle: "” Authentication of the geographical origin of Roselle (Hibiscus sabdariffa L) using various spectroscopies”",
        italic: "NIR, low-field NMR and fluorescence. Food Control. 114,",
        pp: "August 2020, 107231.",
        url: "#",
      },
	  {
        title: "Amal Yasein MOHAMMED, Musa Hago ELFAKİ, Mohamed Ahamed EL HADO, Abdalbasit Adam MARİOD ",
        subtitle: "” The Impact of PoultryProduction on Empowering of RuralWomen Development.”",
        italic: "Yuzuncu Yil University Journal of Agricultural Science YYÜ TAR BİL DERG (YYU J AGR SCI)30 (1): 204-210,",
        pp: "(2020).",
        url: "#",
      },
	  {
        title: "Ahmed, H.O.A. , Wang,  C.M., Mariod A.A. , Hammoda   T.A.A. ",
        subtitle: "” Camellia oil saponins: Solid phase extraction and its effect on mice blood and organs,”",
        italic: "Grasas Y Aceites 2 (71): April-June of 2020. https://doi.org/10.3989/gya.1171182.,",
        pp: "(2020).",
        url: "#",
      },
	  {
        title: "Mohammed Mohammed Ahmed, Yousif Mohamed Ahmed Idris, Abdalbasit Mariod ",
        subtitle: "” Levels of 3-Monochloropropane-1,2-Diol (3-MCPD) in Sudanese flat bread (Aish Baladi).,”",
        italic: "Singapore Journal of Scientific Research,",
        pp: "10(2):10-16,(2020).",
        url: "#",
      },
	  {
        title: "Abdalbasit Mariod, Maznah Ismail, Hasila Sekar. ",
        subtitle: "”Comparison of supercritical fluid and solvent extraction methods in extracting bioactive compounds and minor components of rice bran oil,”",
        italic: "Carpathian Journal of Food Science And Technology 12(4), 113-124,",
        pp: "(2020).",
        url: "https://doi.org/10.34302/crpjfst/2019.11.6.1",
      },
	  {
        title: "Suzy Munir Salama and Abdalbasit Adam Mariod,",
        subtitle: "” The Efficacy of Processing Strategies on the Gastroprotective Potentiality of Chenopodium quinoa Seeds,”",
        italic: "Scientific World Journal, Hindawi,",
        pp: "Volume 2020 |Article ID 6326452, (2020).",
        url: "https://doi.org/10.1155/2020/6326452",
      },
	  {
        title: "Elsayed, N.A, E.E.M. Ahmad, A. A. Mariod. ",
        subtitle: "” Influence of Extraction Methods on Thermal Properties and Antimicrobial Activity of Moringa peregrina Seed Oil Journal of Microbiology, Biotechnology and Food Sciences,”",
        italic: ",",
        pp: "(2020).",
        url: "#",
      },
	  {
        title: "Mariod A.A.",
        subtitle: "” The Legislative Status of Edible Insects in the World. In: Adam Mariod A. (eds) African Edible Insects As Alternative Source of Food, Oil, Protein and Bioactive Components,”",
        italic: "Springer, Cham,",
        pp: "(2020).",
        url: "#",
      },
	  	  {
        title: "Mariod A.A.",
        subtitle: "” Sorghum Bug (Agonoscelis pubescens) as a Source of Edible Oil, Protein, and Gelatin. In: Adam Mariod A. (eds) African Edible Insects As Alternative Source of Food, Oil, Protein and Bioactive Components,”",
        italic: "Springer, Cham,",
        pp: "(2020).",
        url: "#",
      },
	  	  {
        title: "Mariod A.A.",
        subtitle: "” Watermelon Bug (Aspongopus viduatus) as a Source of Edible Oil, Protein, and Gelatin. In: Adam Mariod A. (eds) African Edible Insects As Alternative Source of Food, Oil, Protein and Bioactive Components.”",
        italic: "Springer, Cham,",
        pp: "(2020).",
        url: "#",
      },
	  	  {
        title: "Mariod A.A.",
        subtitle: "” Nutrient Composition and Bioactive Components of Ants (Oecophylla smaragdina Fabricius). In: Adam Mariod A. (eds) African Edible Insects As Alternative Source of Food, Oil, Protein and Bioactive Components,”",
        italic: "Springer, Cham,",
        pp: "(2020).",
        url: "#",
      },
	   {
        title: "Mariod A.A.",
        subtitle: "” Nutrient Composition of Desert Locust (Schistocerca gregaria). In: Adam Mariod A. (eds) African Edible Insects As Alternative Source of Food, Oil, Protein and Bioactive Components,”",
        italic: "Springer, Cham,",
        pp: "(2020).",
        url: "#",
      },
	   {
        title: "Mariod A.A.",
        subtitle: "”Nutrient Composition of Mealworm (Tenebrio molitor). In: Adam Mariod A. (eds) African Edible Insects As Alternative Source of Food, Oil, Protein and Bioactive Components,”",
        italic: "Springer, Cham,",
        pp: "(2020).",
        url: "#",
      },
	   {
        title: "Koko M.Y.F., Mariod A.A.",
        subtitle: "” Sensory Quality of Edible Insects. In: Adam Mariod A. (eds) African Edible Insects As Alternative Source of Food, Oil, Protein and Bioactive Components,”",
        italic: "Springer, Cham,",
        pp: "(2020).",
        url: "#",
      },
	   {
        title: "Sama M.N. Attiyah.",
        subtitle: "”A Mini Review on Immune System and Immunological Diseases: Properties, Classification and Evolutional Aspects,”",
        italic: "Biosc. Biotech. Res. comm,",
        pp: "Vol 13 (4), 1647-1654, (2020).",
        url: "#",
      },
	   {
        title: "Sama M.N. Attiyah.",
        subtitle: "”Immunomodulatory Potential Effects of Pomegranate on Rbl-2h3 Cells,”",
        italic: "Volatiles & Essent. Oils; 8(4): 11662-11674,",
        pp: "(2020).",
        url: "#",
      },
	  {
        title: "Sama M.N. Attiyah,Elsayed HM, Al-Mughales JA, Moharram AB, Abdel- Fattah M",
        subtitle: "”Critical cases of COVID-19 patientscan be predicted by the biomarkers of complete blood count,”",
        italic: "Indian Journal of Science and Technology,",
        pp: "(13(48): 4739-4745. https://doi.org/10.17485/IJST/v13i48.2033 (2020).",
        url: "#",
      },
	  {
        title: "Aly, I., Gouida, M. S., Sayed, H. E. L., Attiyah, S. M. N., Shaker, S., Elleboudy, N. A., & Ghoname, S. I",
        subtitle: "”Efficiency of Three Extracts of Caricapapaya as Molluscicidal and Anti-schistosomal Agents against Biomphalaria alexandrina and Schistosoma mansoni by Flow Cytometry,”",
        italic: "Journal of Pharmaceutical Research International,",
        pp: "32(11), 31-41, (2020).",
        url: "https://doi.org/10.9734/jpri/2020/v32i1130543",
      },
	  {
        title: "Aly, I., Ibrahim, E.H., Hamad, R.S., Rabab S. Hamad, Hoda E. L. Sayed, Sama M. N. Attiyah.",
        subtitle: "”The Protective Role of Toll-Like Receptor Agonist Monophosphoryl Lipid A Against Vaccinated Murine Schistosomiasis,”",
        italic: "Acta Parasit. 65, 652–660,",
        pp: "(2020).",
        url: "https://doi.org/10.2478/s11686-020-00204-3",
      },
	  {
        title: "Fadlelmoula, A., Mudarris, M. and Hariri, M.",
        subtitle: "”Prediction of Live Body Weight Using Body Morphometrical Measurements in Camels (Camelus dromedarius),”",
        italic: "World Journal of Biology and Biotechnology,",
        pp: "5(1): 25-29, (2020).",
        url: "#",
      },
	  {
        title: "Elsayed H. M",
        subtitle: "”Toll Like Receptors (TLRs) Strategies for the Control of Protozoan and Helminthes Parasitic Infections an Updated Review,”",
        italic: "Biosc.Biotech.Res.Comm,",
        pp: "2020;13(4).",
        url: "https://bit.ly/3oHRKW5",
      },
      ]
    },
    {
      year: "2019",
      list: [
        {
          title: "Abdalbasit Adam Mariod, Ekhlas Shawkat Kakil, Youssef Fadlallah Hamed Elneel,",
          subtitle: "” Antibacterial Activity of Zingiber Officinale, Matricaria Chamomilla and Nigella Sativa Extractions on the Growth of Pathogenic Bacteria Isolated from Different Clinical Specimens”, ",
          italic: "Acta Scientific Nutritional Health 3.5: 26-32 ",
          pp: ", (2019).",
          url: "#",
        },
        {
          title: "Haroon Elrasheid Tahir, Zou Xiaobo, Abdalbasit Adm Mariod, Afoakwah Akowuah Newlove,",
          subtitle: "” Nutritional value, bioactive compounds, and antioxidant capacities of honey produced in African regions: A review.”, ",
          italic: "Journal of Apicultural Science. ",
          pp: " 63: 2, 179-200 DOI: https://doi.org/10.2478/jas-2019-0023, (2019)",
          url: "#",
        },
        {
          title: "Haroon Elrasheid Tahir, Li Zhihua, Gustav Komla Mahunu, Zou Xiaobo, Muhammad Arslan, Huang Xiaowei, Zhikun Yang, Abdalbasit Adam Mariod,",
          subtitle: "” Effect of gum Arabic edible coating incorporated with African baobab pulp extract on postharvest quality of cold stored blueberries”, ",
          italic: "Food Science and Biotechnology ",
          pp: "29(2):1–10. DOI: 10.1007/s10068-019-00659-9",
          url: "#",
        },
        {
          title: "Bashir, I. A, Mariod A. A, Banu R, Elyas T. B. , ",
          subtitle: "” Significance of Health Related Predictors of Diabetes in Pima Indians Women. Curr Res Nutr Food Sci” ",
          italic: " ",
          pp: "7(2). DOI : http://dx.doi.org/10.12944/CRNFSJ.7.2.05.(2019) ",
          url: "#",
        },
        {
          title: "Noha Fadle, Abdalbasit Mariod, Hiba Abdel Rahman Ali, Alfatih Ahmed Hasan , ",
          subtitle: "TLC and GC-MS analysis of petroleum ether fraction of fermented wood Nikhra of Acacia seyal ",
          italic: "Eurasian Journal of Forest Science, ",
          pp: "7(1): 23-29, (2019).",
          url: "#",
        },
        {
          title: "Mariod A.A.",
          subtitle: "” Wild Fruits and Its Implications on Food Security and Poverty Alleviation in Sudan. In: Mariod A. (eds) Wild Fruits: Composition, Nutritional Value and Products.”, ",
          italic: "Springer, Cham. ",
          pp: " (2019).",
          url: "#",
        },
		{
          title: "Mariod A.A.",
          subtitle: "” Prospects for Utilization of Wild Fruits. In: Mariod A. (eds) Wild Fruits: Composition, Nutritional Value and Products.”, ",
          italic: "Springer, Cham. ",
          pp: " (2019).",
          url: "#",
        },
		{
          title: "Awad E.E.A., Mariod A.A.",
          subtitle: "”Economic of Wild Fruits and It Is Contribution to Rural People. In: Mariod A. (eds) Wild Fruits: Composition, Nutritional Value and Products.”, ",
          italic: "Springer, Cham. ",
          pp: " (2019).",
          url: "#",
        },
		{
          title: "Sulieman A.M.E., Mariod A.A.",
          subtitle: "”Domestication of Indigenous Fruit Trees. In: Mariod A. (eds) Wild Fruits: Composition, Nutritional Value and Products.”, ",
          italic: "Springer, Cham. ",
          pp: " (2019).",
          url: "#",
        },
		{
          title: "Mariod A.A.",
          subtitle: "”Wild Fruits: Medicinal Use and Health Benefits. In: Mariod A. (eds) Wild Fruits: Composition, Nutritional Value and Products. ”, ",
          italic: "Springer, Cham. ",
          pp: " (2019).",
          url: "#",
        },
		{
          title: "Ahmed R.H.A., Mariod A.A.",
          subtitle: "”Annona squamosa: Phytochemical Constituents, Bioactive Compounds, Traditional and Medicinal Uses. In: Mariod A. (eds) Wild Fruits: Composition, Nutritional Value and Products.”, ",
          italic: "Springer, Cham. ",
          pp: " (2019).",
          url: "#",
        },
		{
          title: "Mustafa S.E., Mohamed R.A., Awad E.E.A., Mariod A.A.",
          subtitle: "”Vangueria madagascariensis: Phytochemical Constituents, Bioactive Compounds, Traditional and Medicinal Uses. In: Mariod A. (eds) Wild Fruits: Composition, Nutritional Value and Products.”, ",
          italic: "Springer, Cham. ",
          pp: " (2019).",
          url: "#",
        },
		{
          title: "Ahmad E.E.M., Mariod A.A.",
          subtitle: "”Balanites aegyptiaca: Phytochemical Constituents, Bioactive Compounds, Traditional and Medicinal Uses. In: Mariod A. (eds) Wild Fruits: Composition, Nutritional Value and Products.”, ",
          italic: "Springer, Cham. ",
          pp: " (2019).",
          url: "#",
        },
		{
          title: "Tahir H.E., Komla M.G., Mariod A.A.",
          subtitle: "”Detarium microcarpum: Chemical Composition, Bioactivities and Uses. In: Mariod A. (eds) Wild Fruits: Composition, Nutritional Value and Products.”, ",
          italic: "Springer, Cham. ",
          pp: " (2019).",
          url: "#",
        },
		{
          title: "Tahir H.E., Komla M.G., Mariod A.A.",
          subtitle: "”Sclerocarya birrea Chemical Composition, Bioactivities and Uses. In: Mariod A. (eds) Wild Fruits: Composition, Nutritional Value and Products.”, ",
          italic: "Springer, Cham. ",
          pp: " (2019).",
          url: "#",
        },
		{
          title: "Abdelrahman G.H., Mariod A.A.",
          subtitle: "”Tamarindus indica: Phytochemical Constituents, Bioactive Compounds and Traditional and Medicinal Uses. In: Mariod A. (eds) Wild Fruits: Composition, Nutritional Value and Products.”, ",
          italic: "Springer, Cham. ",
          pp: " (2019).",
          url: "#",
        },
		{
          title: "Mahunu G.K., Quansa L., Tahir H.E., Mariod A.A.",
          subtitle: "”Irvingia gabonensis: Phytochemical Constituents, Bioactive Compounds, Traditional and Medicinal Uses. In: Mariod A. (eds) Wild Fruits: Composition, Nutritional Value and Products.”, ",
          italic: "Springer, Cham. ",
          pp: " (2019).",
          url: "#",
        },
		{
          title: "Quansah L., Mahunu G.K., Tahir H.E., Mariod A.A.",
          subtitle: "”Parkia biglobosa: Phytochemical Constituents, Bioactive Compounds, Traditional and Medicinal Uses. In: Mariod A. (eds) Wild Fruits: Composition, Nutritional Value and Products.”, ",
          italic: "Springer, Cham. ",
          pp: " (2019).",
          url: "#",
        },
		{
          title: "Tahir H.E., Xiaobo Z., Komla M.G., Adam Mariod A.",
          subtitle: "”Nopal Cactus (Opuntia ficus-indica (L.) Mill) as a Source of Bioactive Compounds. In: Mariod A. (eds) Wild Fruits: Composition, Nutritional Value and Products..”, ",
          italic: "Springer, Cham. ",
          pp: " (2019).",
          url: "#",
        },
		{
          title: " Mariod A.A.",
          subtitle: "”Garcinia binucao: Biochemistry, Functions and Utilization. In: Mariod A. (eds) Wild Fruits: Composition, Nutritional Value and Products.”, ",
          italic: "Springer, Cham. ",
          pp: " (2019).",
          url: "#",
        },
		{
          title: "Fadlelmoula, A. And Kaskous, S.",
          subtitle: "”Effects of Machine Milking on Milk Yield and Cortisol Hormone Changes of Dairy Cows with or without Calves.”, ",
          italic: "Journal of Veterinary and Marine Sciences,",
          pp: "2(1): 46-51, (2019).",
          url: "#",
        },
        ]
    },
    {
      year: "2018",
      list: [
        {
          title: "Ahmed, W. M.,   Mariod,  A.A.,  Yagoub, S. O.,  Cheng, S. F.,",
          subtitle: "“Effect of Nitrogen, NPK and Compost on Protein and Oil Composition of Soybean (Glycine max L merril) Local genotype.” ",
          italic: "Agronomski glasnik,",
          pp: "80,1, 3-18, (2018).",
          url: "#",
        },
        {
          title: "Noha Fadle, Abdalbasit Mariod, Hiba Abdel Rahman Ali, Alfatih Ahmed Hasan,",
          subtitle: " TLC and GC-MS analysis of fermented wood Nikhra petroleum ether fraction of Combretaceae spp. Combretum hartmannianum and Terminalia laxiflora.",
          italic: "Eurasian Journal of Forest Science. ",
          pp: "6, 3, 1 - 7, (2018).",
          url: "#",
        },
        {
          title: "Abdalbasit Adam Mariod, Hibba Hassan, Kamal Mohamed Saeed , ",
          subtitle: "“Production and properties of surfactants from Jatropha curcas oil.“",
          italic: " Eurasian Journal of Forest Science,",
          pp: " 6(1),52-67, (2018).",
          url: "#",
        },
        {
          title: "Haroon Elrasheid Tahir, Zou Xiaobo, Shi Jiyong, Gustav Komla Mahunu, Xiaodong Zhai, Abdalbasit Adam Mariod, ",
          subtitle: "“Quality and postharvest-shelf life of cold-stored strawberry fruit as affected by gum arabic (Acacia senegal) edible coating,“, ",
          italic: "Journal of Food Biochemistry.",
          pp: " (2018),DOI: 10.1111/jfbc.12527.",
          url: "#",
        },
        {
          title: "Haroon Elrasheid Tahir, Zou Xiaobo. Abdalbasit Adam Mariod, Gustav Komla Mahunu, Mohammed A. Y. Abdualrahman,",
          subtitle: " “William Tchabo Assessment of antioxidant properties, instrumental and sensory aroma profile of red and white Karkade/Roselle (Hibiscus sabdariffa L.).”,",
          italic: " Food Measure. ",
          pp: " (2018),DOI 10.1007/s11694-017-9535-0.",
          url: "#",
        },
        {
          title: "Abdalbasit A. Mariod,",
          subtitle: "” Gum Arabic Dietary Fiber. In: A. Mariod, ed., Gum Arabic Structure, Properties, Application and Economics”, ",
          italic: "1st ed. Elsevier. ",
          pp: " (2018).",
          url: "#",
        },
		{
          title: "Abdalbasit A. Mariod,",
          subtitle: "” Chemical properties of gum Arabic. In: A. Mariod, ed., Gum Arabic Structure, Properties, Application and Economics,”, ",
          italic: "1st ed. Elsevier. ",
          pp: " (2018).",
          url: "#",
        },
		{
          title: "Abdalbasit A. Mariod,",
          subtitle: "” Enhancement of color stability in foods by gum Arabic In: A. Mariod, ed., Gum Arabic Structure, Properties, Application and Economics,”, ",
          italic: "1st ed. Elsevier. ",
          pp: " (2018).",
          url: "#",
        },
		{
          title: "Ahmed,  R. H. A., A. A. Mariod ,",
          subtitle: "” Effect of Gum Arabic on The Fecal Bacterial Mass in Healthy Human Volunteers. In: A. Mariod, ed., Gum Arabic Structure, Properties, Application and Economics,”, ",
          italic: "1st ed. Elsevier. ",
          pp: " (2018).",
          url: "#",
        },
		{
          title: "Suzy Munir Salama, Abdalbasit Adam Mariod,",
          subtitle: "” Gastroprotective activity of gum Arabic: A Review In: A. Mariod, ed., Gum Arabic Structure, Properties, Application and Economics, ”, ",
          italic: "1st ed. Elsevier. ",
          pp: " (2018).",
          url: "#",
        },
		{
          title: "Abdalbasit A. Mariod,",
          subtitle: "”Functional properties of gum Arabic In: A. Mariod, ed., Gum Arabic Structure, Properties, Application and Economics,”, ",
          italic: "1st ed. Elsevier. ",
          pp: " (2018).",
          url: "#",
        },
        {
          title: "Ibrahim Aly, Eman E. Taher, Gehan EL nain, Hoda EL Sayed, Faten A. Mohammed, Rabab S. Hamad, Elsayed M. Bayoumy, ",
          subtitle: "“Advantages of bioconjugated silica-coated nanoparticles as an innovative diagnosis for human toxoplasmosis.”. ",
          italic: "Acta Tropica,",
          pp: "Volume 177, January 2018, Pages 19-24. DOI: 10.1016/j.actatropica.2017.09.024 ",
          url: "#",
        },
        ]
      },
      {
      year: "2017",
      list: [
        {
          title: "Sara E. Mustafa, Abdalbasit A. Mariod, Youisf M. Ahmed, Siddig I. Abdelwahab,",
          subtitle: "” Antioxidant Activity and cytotoxicity study of Vangueria madagascariensis Leaf, bark and seed cake Methanolic Extracts.”,",
          italic: " Australian Journal of Basic and Applied Sciences, ",
          pp: "11(3) Special 64-70, (2017).",
          url: "#",
        },
        {
          title: "Sulaiman, H.A., Ahmad, E.E.M., Mariod, AA., Mathäus, B. Salaheldeen M, ",
          subtitle: "“Effect of pretreatment on the proximate composition, physicochemical characteristics and stability of Moringa peregrina oil.”, ",
          italic: "Grasas Aceites,",
          pp: "68 (4), e227. http://dx.doi.org/10.3989/gya.0444171, (2017).",
          url: "#",
        },
        {
          title: " “Sara Mubarak Ahmed Elbadawi, Essa Esmail Mohammad Ahmad, Abdalbasit Adam Mariod, Bertrand Mathäus. “, ",
          subtitle: "Effects of Thermal Processing on Physicochemical Properties and Oxidative Stabilities of Balanities aegyptiaca Kernels and Extracted Oils.  ",
          italic: "Grasas Y Aceites 68, 1, e184, (2017).",
          pp: "#",
          url: "",
        },
		{
          title: " “Sara El Kheir Mustafa, Abdalbasit Adam Mariod,  Yousif Mohamed Ahmed “, ",
          subtitle: "The Potential of Vangueria madagascariensis as a Source for Un-conventional Oil in Sudan.  ",
          italic: "Agricultural and Biological Sciences Journal,",
          pp: "3,( 4), 28-32, (2017).",
          url: "",
        },
		{
          title: " “Mariod, A.A., Yousif M.A. Idris, Nuha M. Osman, Maha A. Mohamed, Awad M.A. Sukrab, Marwa Y. Farag. “, ",
          subtitle: "Effect of fermentation and method of preparation on composition and acrylamide content of Sudanese millet-based fermented foods.  ",
          italic: "Acta Sci. Pol., Technol. Aliment. 16(1), 43–51, (2017).",
          pp: "#",
          url: "",
        },
		{
          title: " “Elrasheid Tahir, H., Xiaobo, Z., Zhihua, L., Jiyong, S., Zhai, X., Wang, S., Adam Mariod, A. “, ",
          subtitle: "Rapid prediction of phenolic compounds and antioxidant activity of Sudanese honey using Raman and Fourier transform infrared (FT-IR) spectroscopy.  ",
          italic: "Food Chemistry 226, 202–211, (2017).",
          pp: "#",
          url: "",
        },
		{
          title: " “Nancy Ibrahim Abdalla, Abdalbasit Adam Mariod, Mohammed Ibrahim Abdelsalam Failmoula and Mohammed Abdelkreim. “, ",
          subtitle: "Estimation of Browse Productivity for Acacia seyal in Alazzazah Area, Blue Nile State, Sudan.  ",
          italic: "Journal of Rangeland Science.",
          pp: "1180-JRS-ISSN: 2008-9996, 7 (4), 341-347, (2017).",
          url: "",
        },
		{
          title: " “Abdelwahab, S.I., Mariod, A.A., Taha M.M.E.,. Zaman F.Q, Abdelmageed A.H.A., Khamis S., Sivasothy Y., Awang K. “, ",
          subtitle: "Chemical composition and antioxidant properties of the essential oil of Cinnamomum altissimum kosterm. (Lauraceae).  ",
          italic: "Arabian Journal of Chemistry.",
          pp: "10, (1), 131–135, (2017).",
          url: "",
        },
		{
          title: " “Mohamed Yousif Ibrahim, Abdalbasit Adam Mariod and Hoyam Adam. “, ",
          subtitle: "Pharmacological and Biological Properties of α-Mangostin IN: Handbook of Food Bioengineering”. Volume VIII. Therapeutic foods (nutraceuticals).  ",
          italic: "",
          pp: " (2017).",
          url: "https://www.elsevier.com/books/book-series/handbook-of-food-bioengineering",
        },
		{
          title: " “Abdalbasit A. Mariod  and Mohammed Salaheldeen. “, ",
          subtitle: "OIL SEED CROPS AND BIODIESEL PRODUCTION: PRESENT AND FUTURE PROSPECTS.  ",
          italic: "Authors: IN: Oil Seed Crops: Yield and Adaptations under Environmental Stress”,  Publisher John Wiley, UK.The Editor Dr. Parvaiz Ahmad:.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 1 - Chrozophora brocchiana (Argessi). Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 1-6.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 2 - Argemone mexicana (Argemone Seed). Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 9-12.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 3 - Cassia obtusifolia (Senna or Sicklepod Seed). Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 13-19.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 4 - Cassia (Senna) occidentalis L. (Coffee Senna). Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 21-25.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 5 - Abutilon pannosum (Forst.) Ragged Mallow. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 27-29.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 6 - Ipomoea quamoclit Cypress Vine (Star Glory). Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 31-34.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 7 - Ipomoea indica Blue Morning Glory. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 35-38.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 8 - Sesamum alatum (Thonn) Winged-Seed Sesame. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 39-43.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 9 - Hibiscus cannabinus L. Kenaf. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 45-51.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 10 - Hibiscus radiatus Roselle. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 53-57.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 11 - Hibiscus sabdariffa L. Roselle. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 59-65.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 12 - Monechma ciliatum Black Mahlab or Mahlab Balady. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 67-72.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 13 - Nigella sativa L. Black Cumin. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 73-80.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 14 - Cucurbits, Cucurbita Species As New Oil Sources. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 81-84.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 15 - Cucumis melo var. flexuosus The Armenian Cucumber or Snake Melon. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 85-88.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 16 - Cucumis sativus Cucumber. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 89-94.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 17 - Cucumis prophetarum Globe Cucumber or Wild Cucumber. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 95-98.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 18 - Citrullus colocynthis Colocynth, Bitter Apple, Bitter Gourd. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 99-105.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 19 - Cucumis melo var. cantalupo Cantaloupe. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 107-111.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 20 - Luffa echinata Bitter Luffa, Bristly Luffa. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 113-115.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 21 - Luffa clynderica Loofah, Sponge Gourd. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 117-123.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 22 - Trigonella foenum-graecum Fenugreek, Bird’s Foot, Greek Hayseed. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 125-130.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 23 - Guizotia abyssinica (L.f.) Cass. Niger. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 131-136.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 24 - Acacia tortilis Umbrella Thorn Tree Seed Oil. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 139-143.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 25 - Annona squamosa L. Sugar Apple Seed Oil. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 145-150.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 26 - The Potential of Sodom Apple (Calotropis procera and Calotropis gigantea) Seed Oil. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 151-155.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 27 - Balanites aegyptiaca Seed Oil. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 157-166.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 28 - Vangueria madagascariensis (Rubiaceae) as New Oil Source. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 167-180.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 29 - Phoenix dactylifera Date Palm Kernel Oil. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 181-185.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 30 - Durio zibethinus (Durian). Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 187-197.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 31 - Jatropha curcas L. Seed Oil. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 199-207.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 32 - Mesua ferrea Nahar Tree Seed Oil. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 209-218.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 33 - Nephelium lappaceum L. Rambutan Kernel Oil. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 219-226.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 34 - Mangifera indica Mango Seed Kernel Oil. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 227-232.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 35 - Moringa oleifera Seed Oil. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 233-241.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 36 - Ziziphus spina-christi (Christ’s Thorn Jujube). Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 243-249.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 37 - Salvadora persica Seed and Seed Oil. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 251-257.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 39 - Adansonia digitata Baobab Seed Oil. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 267-271.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 40 - Sterculia setigera (Karaya Gum Tree) A New Oil Source. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 273-276.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 41 - Albizia lebbeck (L. Benth.) Lebbeck Tree Seed. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 277-281.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 42 - Tessaratoma papillosa Longan Stink Bug. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 285-287.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 43 - Copris nevinsoni Dung Beetle. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 289-292.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 44 - Schistocerca gregaria (Desert Locust) and Locusta migratoria (Migratory Locust). Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 293-297.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 45 - Oecophylla smaragdina Fabricius Weaver Ant. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 299-304.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 46 - Aspongopus viduatus Watermelon Bug As Source of Edible Protein and Oil. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 305-313.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 47 - Agonoscelis pubescens Sorghum Bug as a Source of Edible Protein and Oil. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 315-321.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 48 - Acheta domesticus House Cricket. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 323-325.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 49 - Alphitobius diaperinus the Lesser Mealworm and the Litter Beetle. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 327-330.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 50 - Tenebrio molitor Mealworm. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 331-336.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 51 - Blaptica dubia Cockroaches. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 337-340.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 52 - Macrotermes bellicosus Termite. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 341-346.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 53 - Principles of Oil Extraction, Processing, and Oil Composition. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 347-350.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Mariod, A. A., M. E. Saeed Mirghani and I. Hussein. “, ",
          subtitle: "Chapter 54 - Unconventional Oils From Annuals, Herbs, and Vegetables. Unconventional Oilseeds and Oil Sources,  ",
          italic: "Academic Press: 351-352.",
          pp: " (2017).",
          url: "",
        },
		{
          title: " “Ibrahim Aly, Eman E.Taher , Hoda EL-Sayed , Faten A. Mohammed , Rabab S. Hamad and Elsayed M. Bayoumy. “, ",
          subtitle: "Efficacy Of Soluble Glycoprotein Fraction From Allium Sativum By Size-Exclusion Chromatography On Murine Schistosomiasis Mansoni.  ",
          italic: "Microbial pathogenesis Journal.",
          pp: "(March 2017). DOI: 10.1016/j.micpath.2017.03.039.",
          url: "",
        },
		
        ]
      },
      {
      year: "2016",
      list: [
        {
          title: "Abdalbasit A. Mariod, Yousif M.A. Idris, Nuha M. Osman, Maha A. Mohamed,  Awad M.A. Sukrab, Marwa Y. Farag, B. Matthaus, ",
          subtitle: "“Three Sudanese sorghum-based fermented foods (kisra, Hulu-mar and abreh): Comparison of proximate, nutritional value, microbiological load and acrylamide content.”, ",
          italic: "Ukrainian Journal of Food Science. ",
          pp: "Volume 4. Issue 2, (2016).",
          url: "#",
        },
        {
          title: "Tahir, H.E., Xiaobo, Z.,  Xiaowei, H., Jiyong, S., Mariod, A.A. , ",
          subtitle: "“Discrimination of honeys using colorimetric sensor arrays, sensory analysis and gas chromatography techniques.”. ",
          italic: "Food Chemistry. ",
          pp: " 206, (1), 37–43, (2016).",
          url: "#",
        },
        {
          title: "Mohamed Yousif Ibrahim, Najihah Mohd Hashim, Abdalbasit Adam Mariod, Syam Mohan, Mahmood Ameen Abdulla, Siddig Ibrahim Abdelwahab, Ismail Adam Arbab and Landa Zeenelabdin Ali, ",
          subtitle: "“α-Mangostin from Garcinia mangostana Linn: an updated review of its pharmacological properties.”. ",
          italic: "Arabian Journal of Chemistry. ",
          pp: "(2016), 9, 317–329 doi: http://dx.doi.org/10.1016/j.arabjc.2014.02.001.",
          url: "#",
        },
        {
          title: "Mohamed Yousif Ibrahim, Abdalbasit Adam Mariod and Hoyam Adam, ",
          subtitle: "“Pharmacological and Biological Properties of α-Mangostin IN: Handbook of Food Bioengineering”. Volume VIII. Therapeutic foods (nutraceuticals).  ELSEVIER  under process.”.",
          italic: " ",
          pp: " (2016).",
          url: "#",
        },
        {
          title: "Bogari N, Rednah D, Elkhateeb O, Dannoun A, Amin A A, Porqueddu M, Khogeer S, Attiyah S, Almatrouk E, et al. , ",
          subtitle: "“''Obesity is associated with cardiac disease and the apolipoprotein A5 gene a genetic variant c.553G > T in is associated with an increased risk of coronary artery disease” ",
          italic: "Obesity & Chronic Diseases (ICOCD-2016). ",
          pp: "",
          url: "#",
        },
        {
          title: "Mohamed, H.M.I; El Zubeir, E.M. and Fadlelmoula, A.A. , ",
          subtitle: "”Variation of Microbial Load of Sudanese Nubian Goat’ Milk as Affected by Lactoperoxidase Enzyme System, Stage of Lactation and Storage Temperature.”, ",
          italic: "Research Journal of Microbiology,",
          pp: "11(2-3): 64-69. DOI: 10.3923/jm.2016, (2016).",
          url: "#",
        },
        {
          title: "Ibrahim R. Aly Shalash, Mousa A. M. Ismail, Dina M. H. El Akkad, Hoda EL-Sayed, Eman S. Taher, Marwa EL-Dardiry, Hala M. El-Askary. ",
          subtitle: "Application of Competitive ELISA for Detection of Fasciola Gigantica Tegument-Associated Antigen in Human Fascioliasis.",
          italic: " International Journal of Biology, Pharmacy and Allied Sciences (IJBPAS).",
          pp: " (2016).",
          url: "#",
        },
        ]
      },
      {
      year: "2015",
      list: [
        {
          title: "Haroon Elrasheid Tahir, Zou Xiaobo, Shi Jiyong, Abdalbasit A. Mariod, Tchabo Wiliam, ",
          subtitle: "“Rapid Determination of Antioxidant Compounds and Antioxidant Activity of Sudanese Karkade (Hibiscus sabdariffa L.) Using Near Infrared Spectroscopy.”, ",
          italic: "Food Analytical Methods 02, 1-9. ",
          pp: " (2015).",
          url: "#",
        },
        {
          title: "Nancy Ibrahim Abdalla, Abdelaziz Karamalla Gaiballa, Christoph Kätsch, Mahgoub Sulieman, Abdalbasit Mariod , ",
          subtitle: "“Using MODIS- Derived NDVI and SAVI to Distinguish Between Different Rangeland Sites According to Soil Types in Semi-Arid Areas of Sudan (North Kordofan State).”. ",
          italic: "International Journal of Life Science and Engineering 1, ",
          pp: "(4):150-164, (2015).",
          url: "#",
        },
        {
          title: "Abubaker H. Mohamed1, AbdAlla A. AbdAlla, Abdalbasit Mariod, ",
          subtitle: "“Structural Analysis and 3D-Modeling of FANCD2 Proteins.”, ",
          italic: "International Journal of Bioinformatics and Biomedical Engineering, ",
          pp: "1 (2): 205-210, (2015).",
          url: "#",
        },
        {
          title: "Siddig Ibrahim Abdelwahab, Fouad Abdulrahman Hassan, Abdalbasit Adam Mariod, Sadeq Hasan Al-Sheraji, Manal Mohamed Elhassan Taha, Putri Namrima, Amin Ismail, ",
          subtitle: "“Catha edulis Forsk. (khat): Antioxidative activities and chemical diversities using HPLC-DAD-MS/MS analysis  of some Ethiopian and Yemenis varieties.”. ",
          italic: "Ciência e Técnica Vitivinícola. ",
          pp: "30, (10), 299-323, (2015).",
          url: "#",
        },
        {
          title: "Abdalbasit Adam Mariod, Y. M. A. Idris , ",
          subtitle: "“Aflatoxin AFB1 levels in groundnut and sunflower oils in different Sudanese states”, ",
          italic: "Journal of Food Additives and Contaminants - Part B, ",
          pp: "8(4): 266-270, (2015).",
          url: "#",
        },
        {
          title: "Manahil Abd Elrahman Mukhtar, Abdalbasit Adam Mariod, Mohamed Eltigani Salih, Tjahjono Herwan, ",
          subtitle: "“Effect of Substitution of Fish Oil on Fatty Acid Composition of Laying Hens Egg.”, ",
          italic: "American Journal of Nutrition and Food Science. ",
          pp: "1(2): 38-42 , (2015).",
          url: "#",
        },
        {
          title: "Abdalbasit Adam Mariod, Makarim Mutasim M. Mustafa, Abdelazim Ahmed M. Nour, Mahmood Ameen Abdulla, Sit Foon Cheng. ",
          subtitle: "“Investigation of Oil and Protein Contents of Eight Sudanese Lagenaria siceraria Varieties.”. ",
          italic: "J Am Oil Chem Soc. ",
          pp: "92:483–494, (2015).",
          url: "#",
        },
        {
          title: "Mohamed Abdulkadir Gedi,  Jamilah Bakar, Abdulbasit Adam Mariod,",
          subtitle: " “Optimization of Supercritical Carbon Dioxide (CO2) Extraction of Sardine (Sardinella lemuru Bleeker) Oil using Response Surface Methodology (RSM). ”,",
          italic: "GRASAS Y ACEITES 66 (2), 1-11. ",
          pp: " (2015).",
          url: "#",
        },
        {
          title: "Mohammed Salaheldeen, M.K. Aroua, A.A. Mariod, Sit Foon Cheng, Malik A. Abdelrahman, A.E. Atabani, ",
          subtitle: "“Physicochemical characterization and thermal behavior of biodiesel and biodiesel-diesel blends derived from crude Moringa peregrina seed oil.”, ",
          italic: "Energy Conversion and Management. ",
          pp: "92 (1), 535–542, (2015).",
          url: "#",
        },
        {
          title: "Abdalbasit Mariod, Bertrand Matthäus, K. Eichner, Ismail H. Hussein, ",
          subtitle: "“Content and antioxidant activity of phenolic compounds in three unconventional Sudanese.”,",
          italic: " Acta Sci. Pol., Technol. Aliment. 14(1), 63–69, ",
          pp: " (2015).",
          url: "#",
        },
        {
          title: "Abdalbasit Adam Mariod, Hadia Fadul, ",
          subtitle: "“Extraction and Characterization of Gelatin from Two edible Sudanese insects and its Applications in Ice Cream Making Food Science and Technology International ”, ",
          italic: "",
          pp: "21, (5), 380-391, (2015).",
          url: "#",
        },
        {
          title: "Mariod, A. A.",
          subtitle: "“Extraction, Purification and Modification of Natural Polymers Authors: IN: NATURAL POLYMERS- INDUSTRY TECHNIQUES AND APPLICTIONS. Editor Ololade Olatunji publisher Springer co.”,",
          italic: " ",
          pp: " (2015). ",
          url: "#",
        },
        {
          title: "Kaskous, S and Fadlelmoula, A., ",
          subtitle: "“Immunoglobulin in Colostrum and Health of Newborn Calves (Review).”, ",
          italic: "Scientific Journal of Review, ",
          pp: "4(12): 242-249, (2015).",
          url: "#",
        },
        {
          title: "Fadlelmoula, A., Mudarris, M. and Hariri, M., ",
          subtitle: "“Phenotypic classification based on Body Measurements and Body Features of Some Saudi Camels Types (Camelus dromedarius).”, ",
          italic: "Journal of Camel Practice and Research, ",
          pp: "22(2): 1-6. (ISI, IF=0.09), (2015).",
          url: "#",
        },
        {
          title: "Kaskous, S., Jawad, S. and Fadlelmoula, A. , ",
          subtitle: "“Factors Affecting Daily Milk Yield and Composition during Suckling in Mountain Goats.”, ",
          italic: ". Livestock Research for Rural Development (LRRD),",
          pp: "27(6), (2015).",
          url: "#",
        },
        {
          title: "Fadlelmoula, A. and Kaskous, S., ",
          subtitle: "“Effects of Machine Milking on the Milk yield and Cortisol changes of Dairy Cows with or without Calves,”, ",
          italic: "Submitted for publication in Scientifica journal, ",
          pp: " (2015).",
          url: "#",
        },
		{
          title: "Shehadeh Kaskous and Abdelaziz Fadlelmoula, ",
          subtitle: "“Adaptability of Dairy Cows to Individual Quarter milking System after Changing from Tying to Loose housing System,”, ",
          italic: "Advances in Animal and Veterinary Sciences, ",
          pp: " 3(4):225-232, (2015).",
          url: "#",
        },
        ]
      },
      {
      year: "2014",
      list: [
        {
          title: "Mohammed Salaheldeen, M.K. Aroua, A.A. Mariod, Sit Foon Cheng, Malik A.  Abdelrahman. ",
          subtitle: "“An evaluation of Moringa peregrina seeds as a source for bio-fuel.”, ",
          italic: "Industrial Crops and Products. ",
          pp: "61 (2014) 49–61, (2014).",
          url: "#",
        },
        {
          title: "Abdalbasit Adam Mariod, M. Ismail, N.F. Abd Rahman and B. Matthaus, ",
          subtitle: "“Stability of rice bran oil extracted by two different methods during accelerated shelf life storage”, ",
          italic: "A comparative study  GRASAS Y ACEITES 65 (1) January–March doi: http://dx.doi.org/10.3989/gya.109413, ",
          pp: " (2014).",
          url: "#",
        },
        {
          title: "Abdalbasit Adam Mariod, Noha Fadle, Alfatih Ahmed Hasan, ",
          subtitle: "Short communication: Antimicrobial screening of wood extracts of Combretum hartmannianum, ",
          italic: "Acacia seyal and   Terminalia brownie European Journal of Molecular Biology and Biochemistry. ",
          pp: "1(2): 77-80., (2014).",
          url: "#",
        },
        {
          title: "Manal Abasher Ahmed, Abdalbasit Adam Mariod, Ismail Hassan Hussein, Afaf Kamal-eldin, ",
          subtitle: "“REVIEW: Biochemical Composition and Medicinal Uses of Chrozophora Genus,”, ",
          italic: "International Journal of Pharmacy Review & Research, ",
          pp: "4(4): 227-232, (2014). ",
          url: "#",
        },
        {
          title: "Manal Abasher Ahmed, Abdalbasit Adam Mariod,  Nazik. Mustafa, Ismail Hassan Hussein, ",
          subtitle: "“In-vitro Antimicrobial Activity of Chrozophora Brocchiana Different Extracts,”, ",
          italic: "Indian Journal of Pharma ceutical Science & Research 4(3). ",
          pp: " (2014).",
          url: "#",
        },
        {
          title: "Abdalbasit Adam Mariod, Noha Mohammed Fadl Mohammed, Fatima Omer Nabag, Alfatih Ahmed Hassan, ",
          subtitle: "“Ethnobotanical Study of Three Trees: Indigenous Knowledge on Trees Used as Cosmetic in Khartoum State, Sudan.”, ",
          italic: "Asian Journal of Pharmaceutical Science & Technology. ",
          pp: "4(4): 178-182, (2014).",
          url: "#",
        },
        {
          title: "Nuha Mohammed Ali Omer, El Mugdad Ahmed Al, Mariod, A.A., Mohammed Mokhtar, ",
          subtitle: "“PChemical Reactions Taken Place During deep-fat Frying and Their Products: A review. SUST,”, ",
          italic: "Journal of Natural and Medical Sciences Supplementary Issue 2014:1-17. ",
          pp: "",
          url: "#",
        },
        {
          title: "Abdalbasit Adam Mariod, Yousif Mohamed Ahmed Idris, Nuha Mohamed, ",
          subtitle: "“Composition and Stability of Traditional Processed Sesame Oil.”, ",
          italic: "Innovative Romanian Food Biotechnology, ",
          pp: "15(11):51-57, (2014).",
          url: "#",
        },
		{
          title: "Mariod, A.A.",
          subtitle: "“Short Review: The neuroprotective effects of nigella sativa linn. and it’s bioactive compunds IN: The Black Seed (Nigella sativa) a cure of every ailment.”, ",
          italic: "Al-Madinah Al-Munawarh- Taiba University.",
          pp: "(2014).",
          url: "#",
        },
		{
          title: "Kaskous, S. And Fadlelmoula, A.",
          subtitle: "“The Challenge of Machine Milking in Dromedary Camel (Review).”, ",
          italic: "Scientific journal of review.",
          pp: "3(12): 1004-1017, (2014).",
          url: "#",
        },
		{
          title: "Mohamed, H.A.A.; El Zubeir, I.E.M. and Fadlelmoula, A.A. ",
          subtitle: "“Management, Husbandry and Milk Production in Dairy Farms in Khartoum state.”, ",
          italic: "U. Of K. J. Vet. Med. Anim. Prod.",
          pp: "5(2): 38-52, (2014).",
          url: "#",
        },
		{
          title: "Ali E. Kandeel,  Mamdoh T. Gamal, Ashraf A. Sediek,  Hasan S. Salauddin  and Abdelaziz A.Fadlelmoula.",
          subtitle: "“Seroprevalence of Brucellosis within sheep and goat flocks in Alkamil province in Saudi Arabia.”, ",
          italic: "Bothalia Journal.",
          pp: "44(5): 131-140, (2014).",
          url: "#",
        },
		{
          title: "Mahmoud N. M. A., El Zubeir I. E. M. and Fadlelmoula A. A.",
          subtitle: "“ Effect of Stage of Lactation on Milk Yield and Composition of First Kidder Damascus does in the Sudan.”, ",
          italic: "J Anim Prod Adv.",
          pp: "4(3): 355-362, (2014).",
          url: "#",
        },
        ]
      },
      {
      year: "2013",
      list: [
        {
          title: "Faisal Omer Ahmed, Adil Salim Elsheikh and Abdelrahim Abdalla Hommeida",
          subtitle: "“Current Therapy of Repeat Breeding in Cross-bred Dairy Cows with Diluted Povidone Iodine,“",
          italic: "U of K. J. Vet. Med. & Anim. prod",
          pp: "Vol. 4, No. 2, (60-69), (2013)",
          url: "#",
        },
        {
          title: "Abdalbasit Adam Mariod,",
          subtitle: "“Insect oil and protein: Biochemistry, food and other uses: Review. Agricultural Sciences.“",
          italic: "",
          pp: "4:(9B) 76-80. http://dx.doi.org/10.4236/as.2013.49B013 , (2013) ",
          url: "#",
        },
		{
          title: "Abdalbasit Adam Mariod,Sujarwo Suryaputra, Mohammed Hanafi, Taufik Rohmana, Leonardus B.S. Kardono, Tjahjono Herwan. ",
          subtitle: "“Effect Of Different Processing Techniques On Indonesian Roselle (Hibiscus radiates) Seed Constituents.“",
          italic: "Acta Sci. Pol., Technol. Aliment.",
          pp: "12(4) 2013, 359-364 , (2013) ",
          url: "#",
        },
		{
          title: "Abdalbasit Adam Mariod,Hadia Fadul.",
          subtitle: "“REVIEW: GELATIN, SOURCE, EXTRACTION AND INDUSTRIAL APPLICATIONS. ACTA Scientiarum Polonorum.“",
          italic: "Technol. Aliment",
          pp: "Issue 12 (2),135-147, (2013) ",
          url: "#",
        },
		{
          title: "Maznah Ismail, Abdalbasit Mariod, Sia Soh Pin,",
          subtitle: "“Effects of Preparation Methods on Protein and Amino Acid Contents of Various Eggs Available in Malaysian Local Markets  Acta Sci. Pol., Technol. Aliment. 12(1), 21-31“",
          italic: "",
          pp: " (2013) ",
          url: "#",
        },
        {
          title: "MOHAMED, N. A., MARIOD, A. A., YAGOUB, S. O., and DAGASH, Y. M. I.,",
          subtitle: "“Effect of Irrigation Intervals And Fertilizers On Chemical Composition, Minerals And Fatty Acids Of Safflower (Carthamus tinctorius L.)“",
          italic: "SEED Acta Agronomica Hungarica,",
          pp: "61(3), 227-236, (2013)",
          url: "#",
        },
        {
          title: "Idris,Y.M.A., Ibrahim, Y. A., Mariod, A.A.",
          subtitle: "“The effect of gum arabic on color preservation of dehydrated tomato.“",
          italic: "International Journal of Food Properties, ",
          pp: "16:838–851, (2013)",
          url: "#",
        },
        {
          title: "Idris, Yousif. M. A., Hassan, Safaa. A., Mariod, Abdalbasit. A ",
          subtitle: "“Physicochemical characteristics and aflatoxin levels in two types of Sudanese sesame oil.“, ",
          italic: "J Am Oil Chem Soc (2013) 90:989–998.",
          pp: " ",
          url: "#",
        },
        ]
      },
      {
      year: "2012",
      list: [
        {
          title: "Hassanien, M. F. R., Rohn, S., Oraby,H. F.,  Matthaus,B., and Mariod, A. A.",
          subtitle: "Oilseeds Crops: Agronomy,",
          italic: "Science, and Technology International Journal of Agronomy.",
          pp: "Volume 2012, Article ID 278534, 2 pages doi:10.1155/2012/278534.",
          url: "#",
        },
        {
          title: "Abdalbasit Adam Mariod, Yasir Ali Edris, Sit Foon Cheng, Siddig Ibrahim Abdelwahab",
          subtitle: "“Effect of Germination Periods and Conditions on Chemical Composition, Fatty Acids And Amino Acids of Two Black Cumin Seeds.”",
          italic: "Acta Sci. Pol., Technol. Aliment.",
          pp: "11(4), 401-410, (2012) ",
          url: "#",
        },
        {
          title: "Mariod A.A., Abdelwahab S.I., Elkheir S., Ahmed J.M., Fauzi P.N.M., Chuen Ch.S.,",
          subtitle: "“Antioxidant activity of different parts from Annona squamosa, and Catunaregam nilotica methanolic extract. “",
          italic: "Acta Sci. Pol., Technol. Aliment.",
          pp: "11(3), 249-257, (2012)",
          url: "#",
        },
        {
          title: "Mariod, A.A., Matthäus, B., Eichner, K., Hussein, I. H., Abdelwahab, S. I., Abdul, A.B.",
          subtitle: " “Effects of deodorization on the quality and stability of three unconventional Sudanese oils.“",
          italic: "GIDA 37 (4): 189-196.",
          pp: " (2012)",
          url: "#",
        },
        {
          title: "Abdalbasit Adam Mariod, Sara Yousif Ahmed, Siddig Ibrahim Abdelwahab, Sit Foon Cheng, Ahmed Mohamedain Eltom, Samia Osman Yagoub & Shiou Wah Gouk,",
          subtitle: "“Effects of roasting and boiling on the chemical composition, amino acids and oil stability of safflower seeds.“",
          italic: "International Journal of Food Science and Technology,",
          pp: "47, 1737–1743, (2012)",
          url: "#",
        },
        {
          title: "Abdalbasit Adam Mariod, Siddig Ibrahim Abdelwahab.",
          subtitle: "Sclerocarya birrea an African Tree of Nutritional and Medicinal Uses: Review.",
          italic: "Journal of Food Review International, ",
          pp: "28(4) 375-388, (2012).",
          url: "#",
        },
		{
          title: "Mariod, A.A., Ibrahim, R. M., Ismail, M., & Ismail, N.",
          subtitle: "Antioxidant activity of phenolic rich fractions obtained from kenaf (Hibiscus cannabinus) seedcake toward corn oil oxidation   Grasas Y aceites",
          italic: "",
          pp: "63 (2), 167-174, (2012).",
          url: "#",
        },
		{
          title: "Mohamed Osman Gafar, Abdalbasit Adam Mariod, Abdelgadir Osman, Yassin Mohamed Ibrahim Dagash and Hatim Guma.",
          subtitle: "The Effect of malathion (Organophosphate) and sevin (Carbamate) application on radish (Raphanus sativus L.) growth,",
          italic: "International Research Journal of Agricultural Science and Soil Science 2, 058-062, ",
          pp: " (2012).",
          url: "#",
        },
		{
          title: "Samia Osman Yagoub, WigdanMohamed Ali Ahmed, and A. A. Mariod.",
          subtitle: "Effect of Urea, NPK and Compost on Growth and Yield of Soybean (Glycinemax L.), in Semi-Arid Region of Sudan.",
          italic: "International Scholarly Research Network ISRN Agronomy, ",
          pp: "Volume 2012, Article ID 678124, 6 pages, (2012).",
          url: "#",
        },
		{
          title: "Mariod, A.A., and Abdelwahab, S.I..",
          subtitle: "Sclerocarya birrea: Biochemical Composition, Nutritional and Medicinal Uses–A Review IN: Natural Products: Research Reviews Vol. 1 Gupta,V K., ISBN: 9788170357759. Daya Publisher in English.",
          italic: " ",
          pp: " (2012).",
          url: "#",
        },
		{
          title: "Mahmoud, N. M. A.; El Zubeir, I. E. M and Fadlelmoula A. A.",
          subtitle: "Colostrum composition and performance of Damascus goats raised under Sudan conditions.",
          italic: "Wudpecker Journal of Agricultural Research, ",
          pp: "1(8):341 – 345, (2012).",
          url: "#",
        },
		{
          title: "I.A. Yousif, A.A.  Fadlelmoula and A.M. Ismail.",
          subtitle: "Genetic Variability in the Body Weight of Sudan Desert Goats.",
          italic: "Archives Animal Breeding, ",
          pp: "54(2): 205-211, (2012).",
          url: "#",
        },
        ]
      },
    ]

export default biology
