const mathm = [
    
      {
      year: "2022",
      list: [
        {
          title: "Kanayo K. Asogwa, M.D. Alsulami, B.C. Prasannakumara, Taseer Muhammad. ",
          subtitle: "“Double diffusive convection and cross dffusion effects on Casson fluid over a Lorentz force driven Riga plate in a porous medium with heat sink: An analytical approach”, ",
          italic: "International Communications in Heat and Mass Transfer. ",
          pp: "Vol. 131, February 2022, 105761, (2022).",
          url: "https://doi.org/10.1016/j.icheatmasstransfer.2021.105761",
        },
        {
          title: "Tarig M. Elzaki, Shams A. Ahmed, Mounirah Areshi, Mourad Chamekh, ",
          subtitle: "“Fractional partial differential equations and novel double integral transform”. ",
          italic: " Journal of King Saud University – Science. ",
          pp: "(2022) ",
          url: "https://doi.org/10.1016/j.jksus.2022.101832",
        },
        {
          title: "Adnan, Umar Khan, Naveed Ahmed, Syed Tauseef Mohyud Din, M. D. Alsulami, Ilyas Khan, ",
          subtitle: "“A novel analysis of heat transfer in the nanofluid composed by nanodimaond and silver nanomaterials: numerical investigation”. ",
          italic: "Scientific Reports. ",
          pp: "(2022) 12:1284.",
          url: "https://doi.org/10.1038/s41598-021-04658-x",
        },
        {
          title: "M. C. Jayaprakash, M. D. Alsulami, Bandari Shanker & R. S. Varun Kumar, ",
          subtitle: "“Investigation of Arrhenius activation energy and convective heat transfer efficiency in radiative hybrid nanofluid flow”.",
          italic: "Waves in Random and Complex Media",
          pp: " (2022)",
          url: "https://doi.org/10.1080/17455030.2021.2022811",
        },
        {
          title: "D. O. Soumya, B. J. Gireesha, P. Venkatesh & M. D. Alsulami, ",
          subtitle: "“Effect of NP shapes on Fe3O4 – Ag/kerosene and Fe3O4 – Ag/water hybrid nanofluid flow in suction/injection process with nonlinear-thermal-radiation and slip condition; Hamilton and Crosser's model” ",
          italic: " Waves in Random and Complex Media ",
          pp: "(2022)",
          url: "https://doi.org/10.1080/17455030.2021.2022813",
        },
        ]
      },
    {
    year: "2021",
    list: [
       {
        title: "M.D. Alsulami , Hanaa Abu-Zinadah , Anwar Hassan Ibrahim. ",
        subtitle: "“Machine Learning Model and Statistical Methods for COVID-19 Evolution Prediction” ",
        italic: "Wireless Communications and Mobile Computings. ",
        pp: "Vol. 2021, Article ID 4840488, 6 pages.",
        url: "https://doi.org/10.1155/2021/4840488",
      },
       {
        title: "Mourad Chamekh, Mohamed Ali Latrach, Tarig M. Elzaki. ",
        subtitle: "“Approximate analytical solutions for some obstacle problems” ",
        italic: "Journal of King Saud University–Science. ",
        pp: "Vol. Vol. 33 (2021) 101259.",
        url: "https://www.researchgate.net/publication/347429561",
      },
       {
        title: "J. K. Madhukesh, G. K. Ramesh, M. D. Alsulami & B. C. Prasannakumara. ",
        subtitle: "“Characteristic of thermophoretic effect and convective thermal conditions on flow of hybrid nanofluid over a moving thin needle” ",
        italic: "Waves in Random and Complex Media. ",
        pp: " (2021).",
        url: "https://doi.org/10.1080/17455030.2021.2012303",
      },
      {
        title: "Amjad E. Hamza, Mohamed Z. Mohamed, Eltaib M. Abd Elmohmoud, and M. Magzoub. ",
        subtitle: "“Conformable Sumudu Transform of Space-Time Fractional Telegraph Equation” ",
        italic: "Abstract and Applied Analysis. ",
        pp: "Vol. 2021, Article ID 6682994, 6 pages, (2021).",
        url: "https://doi.org/10.1155/2021/6682994",
      },
      {
        title: "Bander N. Almutairi, Ahmed E. Abouelregal, Bandar Bin-Mohsin, M.D. Alsulami, Phatiphat Thounthong. ",
        subtitle: "“Numerical Solution of the Multiterm Time-Fractional Model for Heat Conductivity by Local Meshless Technique” ",
        italic: "Complexity. ",
        pp: "Vol. 2021, Article ID 9952562, 10 pages (2021).",
        url: "https://doi.org/10.1155/2021/9952562",
      },
      {
        title: "Isa Abdullahi Baba, Hijaz Ahmad, M.D. Alsulami, khadija M. Abualnaja, Mohamed Altanji. ",
        subtitle: "“A mathematical model to study resistance and non-resistance strains of influenza“ ",
        italic: "Results in Physics. ",
        pp: "Vol. 26, (2021).",
        url: "https://doi.org/10.1016/j.rinp.2021.104390",
      },
      {
        title: "M. D. Alsulami. ",
        subtitle: "“ Computational mathematical techniques model for investment strategies”  ",
        italic: "Applied Mathematical Sciences, ",
        pp: "Vol. 15, no. 1, 47-55, (2021).",
        url: "https://doi.org/10.12988/ams.2021.914378",
      },
      {
        title: "Md. Fayz-Al-Asad, Md. Nur Alam, Hijaz Ahmad, M.M.A. Sarker, M.D. Alsulami, Khaled A. Gepreel. ",
        subtitle: "“Impact of a closed space rectangular heat source on natural convective flow through triangular cavity “",
        italic: " Results in Physics. ",
        pp: "Vol. 23,  (2021).",
        url: "https://doi.org/10.1016/j.rinp.2021.104011",
      },
      {
        title: "Mohamed Z. Mohamed, Tarig M. Elzaki, Mohamed S. Algolam, Eltaib M. Abd Elmohmoud , and Amjad E. Hamza. ",
        subtitle: "“New Modified Variational Iteration Laplace Transform Method Compares Laplace Adomian Decomposition Method for Solution Time-Partial Fractional Differential Equations”",
        italic: " Journal of Applied Mathematics, ",
        pp: "Vol. (2021) |Article ID 6662645  ",
        url: "https://doi.org/10.1155/2021/6662645",
      },
      {
        title: "Mourad Chamekh, Mohamed Ali Latrach, Tarig M. Elzaki. ",
        subtitle: "“Approximate analytical solutions for some obstacle problems” ",
        italic: "Journal of King Saud University – Science. ",
        pp: "Vol. 33, Issue 2, (2021).  ",
        url: "https://doi.org/10.1016/j.jksus.2020.101259",
      },
      {
        title: "Saad J. Almalki, Tahani A. Abushal , M. D. Alsulami, and G. A. Abd-Elmougod.",
        subtitle: " “Analysis of Type-II Censored Competing Risks’ Data under Reduced New Modified Weibull Distribution” ",
        italic: "Complexity. ",
        pp: "Vol. 2021, Article ID 9932840, 13 pages, (2021).  ",
        url: "https://doi.org/10.1155/2021/9932840",
      },
      {
        title: "Shams A.Ahmed, Tarig M.Elzaki, Mohamed Elbadri, Mohamed Z.Mohamed. ",
        subtitle: "“Solution of partial differential equations by new double integral transform (Laplace - Sumudu transform)” ",
        italic: "Ain Shams Engineering Journal. ",
        pp: "Vol. 12, No. 1, (2021)",
        url: "https://doi.org/10.1016/j.asej.2021.02.032",
      },
      {
        title: "Waleed M. Osman, Tarig M. Elzaki, Nagat A.A. Siddig. ",
        subtitle: "“Modified Double Conformable Laplace Transform and Singular Fractional Pseudo-Hyperbolic and Pseudo-Parabolic Equations” ",
        italic: "Journal of King Saud University – Science. ",
        pp: "Vol. 33, Issue 3, (2021).",
        url: "https://doi.org/10.1016/j.jksus.2021.101378",
      },
      {
        title: "Waleed M. Osman, Tarig M. Elzaki, Nagat A. A. Siddig. ",
        subtitle: "”Solution of Fractional Telegraph Equations by Conformable Double Convolution Laplace Transform” ",
        italic: "Communications in Mathematics and Applications. ",
        pp: "Vol. 12, No. 1, pp. 51–58, (2021).",
        url: "#",
      },
      {
        title: "Fuzhang Wang, Muhammad Imran Asjad, Muhammad Zahid, Azhar Iqbal, Hijaz Ahmad, M.D. Alsulami. ",
        subtitle: "“Unsteady thermal transport flow of Casson nanofluids with generalized Mittag-Leffler kernel of Prabhakar's type” ",
        italic: "Journal of Materials Research and Technology ",
        pp: "Vol.14, September–October 2021, pp. 1292-1300(2021) ",
        url: "#",
      },
      {
        title: "Fuzhang Wanga, Imtiaz Ahmad, Hijaz Ahmad, M.D. Alsulami, K.S. Alimgeer, Clemente Cesarano, Taher A. Nofal. ",
        subtitle: "”Meshless method based on RBFs for solving three-dimensional multiterm time fractional PDEs arising in engineering phenomenons” ",
        italic: "Journal of King Saud University – Science ",
        pp: "Volume 33, Issue 8, December 2021, 1016",
        url: "https://doi.org/10.1016/j.jksus.2021.101604",
      },
      ]
    },
    {
    year: "2020",
    list: [
      {
        title: "Aisha Abdullah Alderremy , Mourad Chamekh , and Fadhel Jeday, ",
        subtitle: "“Semi-analytical solution for a system of competition with production a toxin in a chemostat “",
        italic: " Journal of Mathematics and Computer Science, ",
        pp: "Vol. 20, PP. 155–160, (2020). DOI: 10.22436/jmcs.020.02.07",
        url: "#",
      },
      {
        title: "Alla M. Elsheikh, and Tarig M. Elzaki, ",
        subtitle: "“Modified Variation Iteration Method And Laplace – Elzaki Transform For Solve Hirota, Schrodinger And Complex MKDV Equations”, ",
        italic: "World Journal of Engineering Research and Technology WJERT. ",
        pp: "Vol. 6, Issue 6, PP. 128-136, (2020).",
        url: "#",
      },
      {
        title: "Eltaib M. Abd Elmohmoud, and Tarig M. Elzaki,",
        subtitle: "” New Method With Laplace Transform To Solve Nonlinear PDES”, ",
        italic: "World Journal of Engineering Research and Technology WJERT. ",
        pp: "Vol. 6, Issue 4, (2020).",
        url: "#",
      },
      {
        title: "Olufemi Elijah Ige, Razaq Adekola Oderinu, and Tarig M. Elzaki,",
        subtitle: "” Numerical Simulation of The Nonlinear Coupled Jaulent-Miodek Equation by Elzaki Transform-Adomian Polynomial Method”, ",
        italic: "Advances in Mathematics: Scientific Journal. ",
        pp: "Vol. 9, no.12, PP. 10335–10355, (2020).",
        url: "https://doi.org/10.37418/amsj.9.12.25",
      },
      {
        title: "M. D. Alsulami, ",
        subtitle: "“Assorting Faces by Singular Value Decomposition” ",
        italic: "IOSR Journal of Mathematics (IOSR-JM) ",
        pp: "Vol. 16, Issue 6, PP 01-05, (2020). DOI: 10.9790/5728-1606040105",
        url: "#",
      },
      {
        title: "M. D. Alsulami, ",
        subtitle: "” Stochastic Modeling of Infectious Disease” ",
        italic: "International Journal of Innovation in Science and Mathematics ",
        pp: "Volume 8, Issue 6, (2020).",
        url: "#",
      },
      {
        title: "Moh A. Hassan, Tarig M. Elzaki,",
        subtitle: "” Double Elzaki Transform Decomposition Method for Solving Non-Linear Partial Differential Equations”",
        italic: " Journal of Applied Mathematics and Physics, ",
        pp: "Vol. 8, PP. 1463-1471, (2020). DOI: 10.4236/jamp.2020.88112",
        url: "#",
      },
      {
        title: "Mourad Chamekh, Mohamed Ali Latrach, and Yves Renard,",
        subtitle: "” Frictional self-contact problem of elastic rods” ",
        italic: "Journal of King Saud University – Science. ",
        pp: "Vol. 32, Issue 1, Pages 828-835, (2020).",
        url: "https://doi.org/10.1016/j.jksus.2019.02.017",
      },
      {
        title: "Shams A. Ahmed, Tarig M. Elzaki, and Abdelgabar Adam Hassan,",
        subtitle: "” Solution of Integral Differential Equations by New Double Integral Transform (Laplace–Sumudu Transform)” ",
        italic: "Abstract and Applied Analysis ",
        pp: "Vol. 2020, Article ID 4725150, 7 pages, (2020).",
        url: "https://doi.org/10.1155/2020/4725150",
      },
      {
        title: "Mahmod M. Sh. Amrir ,",
        subtitle: "” تأثير القوى العاملة و البطالة على الناتج القومي المحلي باستخدام أنموذج البيانات المزدوجة (Panel Data) - دراسة تحليلية على الدول العربية للفترة (2000 -2018”",
        italic: ", الأطروحة ( العلوم الصرفة)",
        pp: "",
        url: "#",
      },
      ]
    },
    {
      year: "2019",
      list: [
        {
          title: "Aisha Abdullah Alderremy, Tarig M. Elzaki, and Mourad Chamekh,",
          subtitle: "” Modified Adomian Decomposition Method to Solve Generalized Emden–Fowler Systems for Singular IVP”, ",
          italic: "Mathematical Problems in Engineering ",
          pp: "Vol. 2019, Article ID 6097095, 6 pages, (2019).",
          url: "https://doi.org/10.1155/2019/6097095",
        },
        {
          title: "Huda Ibrahim Osman Bashir, Mona Magzoub Mohammed Ahmed Hassan, Fatin Ali Mohamed Saeed, Nesreen Sirelkhtam Elmki Abdalla, Mubarak Dirar Abdallah & Sawsan Ahmed Elhouri Ahmed,",
          subtitle: "” Applications of Kamal Transform to Mechanics & Electrical Circuits Problems”, ",
          italic: "Global Journal of Engineering Science and Researches. ",
          pp: "Vol. 6, no. 10, (2019) DOI- 10.5281/zenodo.3475118",
          url: "#",
        },
        {
          title: "Mahmod Mohamed Shakoor Amrir,",
          subtitle: "” Comparing Three Different Estimators of fuzzy hazard Rate Function for Mixed Failure to Time Model”, ",
          italic: "IJCSNS International Journal of Computer Science and Network Security, ",
          pp: "VOL.19 No.12, (2019)",
          url: "#",
        },
        {
          title: "Mourad Chamekh, Nabiha Brik and Malek Abid, ",
          subtitle: "” Mathematical and numerical study of the concentration effect of red cells in blood” ",
          italic: "Journal of King Saud University - Science. ",
          pp: "Vol. 31, Issue 4, PP. 1463-1470. (2019).",
          url: "#",
        },
        {
          title: "Mourad Chamekh, Tarig M. Elzaki, and Nabiha Brik, ",
          subtitle: "“Semi analytical solution for some proportional delay diferential equations”, ",
          italic: "SN Applied Sciences ",
          pp: "Vol. 2019, (2019).",
          url: "https://doi.org/10.1007/s42452-018-0130-8",
        },
        {
          title: "Tarig M. Elzaki and A. A. Ishag,",
          subtitle: "” Modified Laplace Transform and Ordinary Differential Equations with Variable Coefficients”, ",
          italic: "World Engineering & Applied Sciences Journal. ",
          pp: "Vol. 10, no. 3, PP. 79-84, (2019).",
          url: "#",
        },
        {
          title: "Tarig M. Elzaki, Adil Mousa,",
          subtitle: "” On the convergence of triple Elzaki transform”, ",
          italic: "SN Applied Sciences (2019).",
          pp: "",
          url: "https://doi.org/10.1007/s42452-019-0257-2",
        },
        {
          title: "Tarig M. Elzaki, Yassir Daoud and J. Biazar, ",
          subtitle: "“Decomposition Method for Fractional Partial Differential Equations Using Modified Integral Transform” ",
          italic: "World Applied Sciences Journal. ",
          pp: "Vol. 37, no. 1, PP. 18-24, (2019)",
          url: "#",
        },
        ]
    },
    {
      year: "2018",
      list: [
        {
          title: "Mourad Chamekh, Tarig. M. Elzaki, ",
          subtitle: "“Explicit solution for some generalized fluids in laminar flow with slip boundary conditions” ",
          italic: "Journal of Mathematics and computer science. ",
          pp: "Vol. 18, PP. 272–281, (2018). doi: 10.22436/jmcs.018.03.03",
          url: "#",
        },
        {
          title: "Mourad Chamekh, Abdeljabbar Ghanmi, Samah Horrigu,",
          subtitle: "” Iterative Approximation of Positive Solutions for Fractional Boundary Value Problem on the Half-line”",
          italic: " Published by Faculty of Sciences and Mathematics, University of Nis, Serbia. ",
          pp: "Vol. 32, no. 18, PP. 6177–6187, (2018).",
          url: "https://doi.org/10.2298/FIL1818177C",
        },
        {
          title: "Musa A.A. Jawarneh, ",
          subtitle: "“Pseudo Recrrent Manifolds“",
          italic: " International Journal of Engineering, Science and Mathematics,",
          pp: " Vol. 7 Issue 2, (2018).",
          url: "#",
        },
        {
          title: "Musa A. A. Jawarneh, ",
          subtitle: "“Quasi Jawarneh Manifolds“, ",
          italic: "International Journal for Research in Applied Science & Engineering Technology (IJRASET).",
          pp: "Vol. 6, Issue IV, (2018).",
          url: "#",
        },
        {
          title: "Tarig M. Elzaki, Mourad Chamekh,",
          subtitle: " “New transform iterative method for solving some Klein-Gordon equations Aisha Abdullah Alderremya”,",
          italic: " Results in Physics. ",
          pp: "Vol. 10, PP. 655–659, (2018).",
          url: "#",
        },
        {
          title: "Tarig M. Elzaki, Mourad Chamekh,",
          subtitle: "” Solving Nonlinear Fractional Differential Equations using a New Decomposition Method”, ",
          italic: "Universal Journal of Applied Mathematics & Computation. ",
          pp: "Vol. 6, PP. 27-35, (2018).",
          url: "#",
        },
        {
          title: "Mahmod M. Sh. Amrir, ",
          subtitle: "“الطاقة المتجددة و أثرها على النمو الاقتصادي في الاردن”. ",
          italic: "وقائع المؤتمر الاتحاد الاحصائيين العرب في الأردن",
          pp: "",
          url: "#",
        },
        ]
      },
      {
      year: "2017",
      list: [
        {
          title: "M. Jawarneh, S. Samui, U. De,",
          subtitle: "” Projective Curvature Tensor on (K, µ)-Contact Space Forms”,",
          italic: " International Journal of Pure and Applied Mathematics. ",
          pp: "Vol. 113, no. 3, 425-439, (2017). doi: 10.12732/ijpam.v113i3.5",
          url: "#",
        },
        {
          title: "Muhammad Suleman, Tarig. M. Elzaki, Qingbiao Wu, Naveed Anjum, and Jamshaid Ul Rahman, ",
          subtitle: "“New Application of Elzaki Projected Differential Transform Method”, ",
          italic: "Journal of Computational and Theoretical Nanoscience Vol. 14, 631–639, (2017).",
          pp: "#",
          url: "Nabiha Brik, Mourad Chamekh,",
        },
        {
          title: " “Numerical Treatment of A Nonlinear Hyperbolic Equation “, ",
          subtitle: "Mediterranean Journal of Modeling and Simulation. ",
          italic: "Vol. 7, PP. 049-058, (2017).",
          pp: "#",
          url: "",
        },
        ]
      },
      {
      year: "2016",
      list: [
        {
          title: "Alla M. Elsheikh and Tarig M. Elzaki, ",
          subtitle: "“Modified Variational Iteration Method for Solving Fourth Order Parabolic PDEs With Variable Coefficients”, ",
          italic: "Global Journal of Pure and Applied Mathematics. ",
          pp: "Vol. 12, no. 2, pp. 1587-1592, (2016).",
          url: "#",
        },
        {
          title: "Mourad Chamekh, ",
          subtitle: "“Existence of Solutions for a Fractional and Non-Local Elliptic Operator”. ",
          italic: "Journal of Applied & Computational Mathematics. ",
          pp: "Vol. 5, no. 6, (2016) DOI: 10.4172/2168-9679.1000335",
          url: "#",
        },
        {
          title: "Muhammad Suleman, Tarig M. Elzaki, Jamshaid Ul Rahman, and Qingbiao Wu, ",
          subtitle: "“A Novel Technique to Solve Space and Time Fractional Telegraph Equation”. ",
          italic: "Journal of Computational and Theoretical Nanoscience. ",
          pp: "Vol. 13, 1536–1545, (2016).",
          url: "#",
        },
        {
          title: "Musa A.A. Jawarneh, ",
          subtitle: "“Jawarneh Manifold with Semi Symmetric Metric Connection”.",
          italic: " IOSR Journal of Mathematics. ",
          pp: "Vol. 12, no. 5, PP 18-21, (2016)",
          url: "#",
        },
        {
          title: "Musa A. A. Jawarneh, ",
          subtitle: "“Quasi Al-Watani Manifolds” ",
          italic: "Fundamental Journal of Mathematics and Mathematical Sciences ",
          pp: "Vol. 6, no. 1, 2016, Pages 45-50",
          url: "#",
        },
        {
          title: "Musa A. A. Jawarneh, ",
          subtitle: "”Nearly Quasi Al-Watani Manifolds”, ",
          italic: "International Arab Conference on Mathematics and Computations, Zarqa University, Jordan,",
          pp: "(2016).",
          url: "#",
        },
        {
          title: " Mahmod M. Sh. Amrir ",
          subtitle: "التوزيعات المختلطة و التوزيهات الملوثة - دراسة مقارنة",
          italic: " مجلة الاتحاد الاحصائيين العرب (2016).",
          pp: "",
          url: "#",
        },
        ]
      },
      {
      year: "2015",
      list: [
        {
          title: "Alla M. Elsheikh & Tarig. M. Elzaki, ",
          subtitle: "“Variation Iteration Method for Solving Porous Medium Equation”, ",
          italic: "International Journal of Development Research ",
          pp: "Vol. 5, Issue, 06, pp. 4677-4680, (2015).",
          url: "#",
        },
        {
          title: "Amjad Ezoo Hamza & Tarig. M. Elzaki, ",
          subtitle: "“Application of Homotopy Perturbation and Sumudu Transform Method for Solving Burgers Equations”. ",
          italic: "American Journal of Theoretical and Applied Statistics. ",
          pp: "Vol. 4, No. 6, pp. 480-483, (2015). doi: 10.11648/j.ajtas.20150406.18.",
          url: "#",
        },
        {
          title: "Hussam E. Hashim & Tarig. M. Elzaki, ",
          subtitle: "“Solving Singular Partial Integro Differential Equations Using Taylor Series”, ",
          italic: "International Journal of Innovative Science, Engineering & Technology, ",
          pp: "Vol. 2 Issue 4, pp 501-506, (2015).",
          url: "#",
        },
        {
          title: "Mohamed Elbadri & Tarig. M. Elzaki, ",
          subtitle: "“New Modification of Homotopy Perturbation Method and the Fourth - Order Parabolic Equations with Variable Coefficients”. ",
          italic: "Pure and Applied Mathematics Journal. ",
          pp: "Vol. 4, No. 6, pp. 242-247, (2015). doi: 10.11648/j.pamj.20150406.13.",
          url: "#",
        },
        {
          title: "Mohand M. Abdelrahim Mahgob&Tarig. M. Elzaki, ",
          subtitle: "“Solution of Partial Integro-Differential Equations by Elzaki Transform Method”, ",
          italic: "Applied Mathematical Sciences, ",
          pp: "Vol. 9, no. 6, 295 – 303, (2015).",
          url: "http://dx.doi.org/10.12988/ams.2015.411984",
        },
        {
          title: "Mohand M. Abdelrahim Mahgob & Tarig. M. Elzaki, ",
          subtitle: "“Elzaki Transform and Integro-Differential Equation with a Bulge Function”, ",
          italic: "IOSR Journal of Mathematics (IOSR-JM). ",
          pp: "Vol. 11, Issue 2, PP 25-28, (2015). DOI: 10.9790/5728-11232528.",
          url: "#",
        },
        {
          title: "Mohannad H. Eljaily, Tarig M. Elzaki. ",
          subtitle: "“Solution of Linear and Nonlinear Schrodinger Equations by Combine Elzaki Transform and Homotopy Perturbation Method”. ",
          italic: "American Journal of Theoretical and Applied Statistics. ",
          pp: "Vol. 4, No. 6, 2015, pp. 534-538, (2015). doi: 10.11648/j.ajtas. 20150406.24.",
          url: "#",
        },
        {
          title: "Mohammed A. Bajaber &Tarig. M. Elzaki,",
          subtitle: " “New Theorem (Bajaber Theorem) to Find the Division Remainder of Polynomials”,",
          italic: "International journal of Multidisciplinary Research and information, IJMRI. ",
          pp: "Vol. 1, no. 3:159-163 , (2015).",
          url: "#",
        },
        {
          title: "Mourad Chamekh, ",
          subtitle: "“Non-linear Stability Criterion in Numerical Approximation of Hyperelastic Rods”, ",
          italic: "Universal Journal of Engineering Mechanics. ",
          pp: "Vol. 3, 45-52, (2015).",
          url: "#",
        },
        {
          title: "Musa A.A. Jawarneh, ",
          subtitle: "“AL-Watani Manifold Admitting Semi Symmetric Metric Connection”,",
          italic: " Pure Mathematical Sciences, ",
          pp: "Vol. 4, no. 1, 1-8, (2015).",
          url: "#",
        },
        {
          title: "Musa A.A. Jawarneh, ",
          subtitle: "“A Class of Riemannian Manifolds with Special Form of Curvature Tensor”, ",
          italic: "British Journal of Mathematics & Computer Science, ",
          pp: "Vol. 7. No 3: 191-196, (2015).",
          url: "#",
        },
        {
          title: "Muhammad Suleman, Qingbiao Wu, T. M. Elzaki, ",
          subtitle: "“Explicit Analytic Solution of Vibration Equation for large domain by mean of the Elzaki projected Differential Transform Method”,",
          italic: " Journal of Advances in Mathematics, ",
          pp: "Vol .11, no. 5, pp. 5244- 5257, (2015). ",
          url: "#",
        },
        {
          title: "Shams A. Ahmed &Tarig. M. Elzaki, ",
          subtitle: "“Solution of Heat and Wave – Like Equations by Adomian Decomposition Sumudu Transform Method”, ",
          italic: "British Journal of Mathematics & Computer Science. ",
          pp: "Vol. 8, no. 2, 101-111, (2015).",
          url: "#",
        },
        {
          title: "Tarig M. Elzaki & Sadah A. Alkhateeb, ",
          subtitle: "“Modification of Sumudu Transform \"Elzaki Transform\" and Adomian Decomposition Method”, ",
          italic: "Applied Mathematical Sciences, ",
          pp: "Vol. 9, no. 13, 603 – 611, (2015).",
          url: "http://dx.doi.org/10.12988/ams.2015.411968",
        },
        {
          title: "Tarig M. Elzaki & Hwajoon Kim, ",
          subtitle: "“The Solution of Radial Diversity and Shock Wave Equations by Elzaki Variational Iteration Method”, ",
          italic: "International Journal of Mathematical Analysis ",
          pp: "Vol. 9, no. 22, 1065 – 1071, (2015).",
          url: "http://dx.doi.org/10.12988/ijma.2015.5242",
        },
        {
          title: "Tarig M. Elzaki & Badriah A.S. Alamri, ",
          subtitle: "“Combination of Transform Methods for Solving Linear and Nonlinear Differential Equations with Proportional Delay”, ",
          italic: "International Mathematical Forum, ",
          pp: "Vol. 10, no. 10, 467 – 476, (2015).",
          url: "#",
        },
        ]
      },
      {
      year: "2014",
      list: [
        {
          title: "Eltaib M. Abd Elmohmoud &Tarig M. Elzaki, ",
          subtitle: "“Elzaki Transform of Derivative Expressed by Heaviside Function”, ",
          italic: "World Applied Sciences Journal. ",
          pp: "Vol. 32 (8): 1686-1689, (2014). DOI: 10.5829/idosi.wasj.2014.32.08.893.",
          url: "#",
        },
        {
          title: "Eman M. A. Hilal & Tarig M. Elzaki, ",
          subtitle: "“Solution of Nonlinear Partial Differential Equations by New Laplace Variational Iteration Method”, ",
          italic: "Journal of Function Spaces, ",
          pp: "Volume 2014, pp. 1-5, (2014).",
          url: "http://dx.doi.org/10.1155/2014/790714",
        },
        {
          title: "Hwajoon Kim &Tarig M. Elzaki, ",
          subtitle: "The Representation on Solutions of Burger’s Equation by Laplace Transform, Int. ",
          italic: "Journal of Math. Analysis, ",
          pp: "Vol. 8, no. 31, 1543 - 1548, (2014).",
          url: "http://dx.doi.org/10.12988/ijma.2014.46185",
        },
        {
          title: "Mohammed E. A. Rabie, &Tarig. M. Elzaki, ",
          subtitle: "“A study of some systems of non linear partial differential equations by using Adomian and modified decomposition methods”, ",
          italic: "academic Jornalsm, Afreican Journal of Mathematics and Computer Science Research, ",
          pp: "Vol. 7(6), pp, 61-67. (2014). DOI: 10.5897/AJMCSR2014.0541.",
          url: "#",
        },
        {
          title: "Shams A. Ahmed and Tarig M. Elzaki, ",
          subtitle: "“A Comparative Study of Sumudu Decomposition Method and Sumudu Projected Differential Transform Method”, ",
          italic: "World Applied Sciences Journal. ",
          pp: "Vol. 31 (10): 1704-1709, (2014). DOI: 10.5829/idosi.wasj.2014.31.10.215.",
          url: "#",
        },
        {
          title: "Tarig M. Elzaki, ",
          subtitle: "“Application of Projected Differential Transform Method on Nonlinear Partial Differential Equations with Proportional Delay in One Variable”, ",
          italic: "World Applied Sciences Journal. ",
          pp: "Vol 30 (3): 345-349, (2014). DOI: 10.5829/idosi.wasj.2014.30.03.1841.",
          url: "#",
        },
        {
          title: "Tarig M. Elzaki & Badriah A.S. Alamri, ",
          subtitle: "“Projected Differential Transform Method and Elzaki Transform for Solving System of Nonlinear Partial Differential Equations”, ",
          italic: "World Applied Sciences Journal. ",
          pp: "Vol. 32 (9): 1974-1979, (2014).DOI: 10.5829/idosi.wasj.2014.32.09.1253.",
          url: "#",
        },
        {
          title: "Tarig M. Elzaki & Hwajoon Kim, ",
          subtitle: "“The Solution of Burger’s Equation by Elzaki Homotopy Perturbation Method”, ",
          italic: "Applied Mathematical Sciences, ",
          pp: "Vol. 8, no. 59, 2931 – 2940, (2014).",
          url: "http://dx.doi.org/10.12988/ams.2014.44314",
        },
        ]
      },
      {
      year: "2013",
      list: [
        {
          title: "K. Al-Ajlouni, S. Shakhatreh, N. AL- Ibraheem , M. A. Jawarneh",
          subtitle: "“Evaluation of Wastewater Discharge from Hospitals in Amman –Jordan“",
          italic: "International Journal of Basic & Applied Sciences",
          pp: "Vol. 13 Issue 4, p44 , (2013)",
          url: "#",
        },
        {
          title: "Elsayed A. Elnour, & Tarig. M. Elzaki,",
          subtitle: "“Solution of Nonlinear Partial Differential Equations by the Combined Laplace Transform and the new Modified Variational Iteration Method“",
          italic: "Wulfenia journal",
          pp: "vol. 20, No. 4, pp. 174-180, (2013) ",
          url: "#",
        },
        {
          title: "Mahmood Mrir,",
          subtitle: "“Comparing Different Estimators for Parameters of Two Gamma Parameters Using Simulation“",
          italic: "IJCSNS International Journal of Computer Science and Network Security",
          pp: "VOL.13 No.12, (2013)",
          url: "#",
        },
        {
          title: "Musa A.A. Jawarneh",
          subtitle: "“Semi-pseudo symmetric manifolds admitting a semi-symmetric metric“",
          italic: "Universal journal of mathematics and mathematical sciences, ",
          pp: "Vol. 3, no.2, 193-204, (2013)",
          url: "#",
        },
        {
          title: "Musa A.A. Jawarneh",
          subtitle: "“Semi-pseudo symmetric manifold admitting a semi-symmetric metric connection“, ",
          italic: "Archives Des Sciences.",
          pp: "Vol.66, no.1, 269-276, (2013)",
          url: "#",
        },
        {
          title: "Tarig. M. Elzaki, Benedict Ita, ",
          subtitle: "“Solutions of Radial Diffusivity and Shock Wave Equationsby Combined Homotopy Perturbation and Elzaki Transform Methods“, ",
          italic: "Asia-Pacific Science and Culture Journal, ",
          pp: "Vol. 2, 18–23, , (2013)",
          url: "#",
        },
        {
          title: "Tarig. M. Elzaki, Eman M.A. Hilal & Sadah. A. Alkhateeb, ",
          subtitle: "“On the Classifications of Hyperbolic and Elliptic Equationswith Exponential Coefficients“,",
          italic: "Science Series Data Report, ",
          pp: "Vol 5, No. 2, pp. 21-25, (2013)",
          url: "#",
        },
        {
          title: "Tarig M. Elzaki, and J. Biazar, ",
          subtitle: "“Homotopy Perturbation Method and Elzaki Transform for Solving System of Nonlinear Partial Differential Equations“, ",
          italic: "World Applied Sciences Journal ",
          pp: "Vol, 24 (7): 944-948, (2013)",
          url: "#",
        },
        {
          title: "Tarig. M. Elzaki, Mohmod M. Sh. Amrir, ",
          subtitle: "“Combine Laplace Transform and Variational Iteration Method to Solve Convolution Differential Equations“, ",
          italic: "The 6th International Conference on Information Technology, ",
          pp: "(2013)",
          url: "#",
        },
        {
          title: "Tarig M. Elzaki, and Salih M. Elzak, ",
          subtitle: "“Application of Tarig Transform to Integral and Integro-Differential Equations“, ",
          italic: "Elixir Appl. Math. ",
          pp: "57  13978-13981, (2013)",
          url: "#",
        },
        ]
      },
      {
      year: "2012",
      list: [
        {
          title: "Mahmood Mrir",
          subtitle: "The Relationship between Information System strategy & Information. Technology strategy",
          italic: "International Journal for Sciences and Technology.",
          pp: " Vol 7, No 2, (2012)",
          url: "#",
        },
        {
          title: "Mohammed E. A. Rabie, & Tarig. M. Elzaki",
          subtitle: "“Solution of Linear Systems of Partial Differential Equationsby Adomian and Modified Decomposition Methods”",
          italic: "Asia-Pacific Science and Culture Journal",
          pp: "Vol. 2, 56–62, 2013© (2012) ",
          url: "#",
        },
        {
          title: "Musa A.A. Jawarneh",
          subtitle: "“Generalized semi-pseudo Ricci symmetric manifold “",
          italic: "International Mathematical Forum",
          pp: "Vol.7,  no. 6, 297 – 303, (2012)",
          url: "#",
        },
        {
          title: "Shams A. Ahmed & Tarig. M. Elzaki",
          subtitle: " “The Solution of Nonlinear Volterra Integro-Differential Equations of Second Kind by Combine Sumudu Transform and Adomain Decomposition Method“",
          italic: "International Journal of Advanced and Innovative Research.",
          pp: " Vol. 2 Issue 12. PP 90-93, (2012)",
          url: "#",
        },
        {
          title: "Tarig. M. Elzaki,",
          subtitle: "“Double Laplace Variational Iteration Method for Solution of Nonlinear Convolution Partial Differential Equations“",
          italic: "Archives Des Sciences (ISI Journal)",
          pp: " Vol. 65, No. 12, PP. 588-593, (2012)",
          url: "#",
        },
        {
          title: "محمود امرير",
          subtitle: "مدى رضا طلاب كلية العلوم والآداب بمحافظة الكامل عن واقع الكلية دراسة ميدانية",
          italic: "مجلة الاتحاد الاحصائيين العرب ",
          pp: "المجلد الأول  JASU العدد الثاني 2012",
          url: "#",
        },
        ]
      },
    ]

export default mathm
