var app = new Vue({
    el: "#app",
    data: {
      selectedYear: 0,
      modalData: {
        "title": "",
        "author": "",
        "faculty": "",
        "date": "",
        "url": "",
        "poster": "",
        "video": "",
    },
      seminars: [
        {
            year: "1442-1443",
            list: [
                {
                    title: "Some Topics in the Convolution Theory",
                    author: "Prof. Tarig M. Elzaki, Faculty of Science & Art (Alkamil)",
                    sponsor: "قسم الرياضيات",
                    date: "20-01-2021",
                    poster: "Files/856/Galleries/7279/55984_semi1.jpg",
                    video: "https://jeddahu-my.sharepoint.com/:v:/g/personal/csa_math_kamil_uj_edu_sa/ERoYKkpnXkBChlRJNBhUh14BqsCkPnQqi7I2eWz_ZLgh6A?e=isqJuT",
                    url: "",
                },
                {
                    title: "Frictional Self-Contact Problem of Elastic Rods",
                    author: "Mourad Chamekh, PhD, Faculty of Science & Art (Alkamil)",
                    sponsor: "قسم الرياضيات",
                    date: "03-02-2021",
                    poster: "Files/856/Galleries/7279/55985_semi2.jpg",
                    video: "",
                    url: "",
                },
                {
                    title: "A High Order Finite Element Method for Elliptic Interface Problems Using Hermite Splines",
                    author: "Luis Zeron, PhD, NMT. USA",
                    sponsor: "قسم الرياضيات",
                    date: "10-02-2021",
                    poster: "Files/856/Galleries/7279/55986_semi3.jpg",
                    video: "",
                    url: "",
                },
                {
                    title: "Stochastic Model for Diminishing Musharakah in Islamic Bank",
                    author: "Majdi D. Alsulami, PhD, Faculty of Science & Art (Alkamil)",
                    sponsor: "قسم الرياضيات",
                    date: "24-02-2021",
                    poster: "Files/856/Galleries/7279/55987_semi4.jpg",
                    video: "https://jeddahu-my.sharepoint.com/:v:/g/personal/csa_math_kamil_uj_edu_sa/EWA8llVCWm5Hg-WaiFsfDQoBQHWZ2XAVkmRKMNTSlHKahQ?e=suYL1f",
                    url: "",
                },
                {
                    title: "Goodness-of-Fit for The Beta Gompertz Distribution",
                    author: "Prof. Hanaa Abu-Zinadah, Faculty of Science",
                    sponsor: "قسم الرياضيات",
                    date: "03-03-2021",
                    poster: "Files/856/Galleries/7279/55988_semi5.jpg",
                    video: "https://jeddahu-my.sharepoint.com/:v:/g/personal/csa_math_kamil_uj_edu_sa/EeKH1tFwDE9DiRAym6oX6w4Bzs8sEHY0pq6_NJsJxG0zOw?e=Cm2nBF",
                    url: "",
                },
                {
                    title: "Jawarneh Manifold",
                    author: "Mussa Jawarneh, PhD, Faculty of Science & Art (Alkamil)",
                    sponsor: "قسم الرياضيات",
                    date: "10-03-2021",
                    poster: "Files/856/Galleries/7279/55989_semi6.jpg",
                    video: "",
                    url: "",
                },
                {
                    title: "Solution of Telegraph Equations by Elzaki-LAPLACE Transform",
                    author: "Prof. Tarig M. Elzaki, Faculty of Science & Art (Alkamil)",
                    sponsor: "قسم الرياضيات",
                    date: "17-03-2021",
                    poster: "",
                    video: "",
                    url: "",
                },
                {
                    title: "Forecasting value-at-risk estimates using GARCH-EVT-copula models",
                    author: "Haslifah Hasim, PhD, Mathematical and Computer Sciences, Heriot-Watt University, Dubai",
                    sponsor: "قسم الرياضيات",
                    date: "24-03-2021",
                    poster: "Files/856/Galleries/7279/55990_semi8.jpg",
                    video: "https://jeddahu-my.sharepoint.com/:v:/g/personal/csa_math_kamil_uj_edu_sa/EZlbXhSGXDtEvOfPV-PTL1oBqslMSk3P6q0Ii6NoANC6OA?e=T1Kn9J",
                    url: "",
                },
                {
                    title: "Modeling and Optimal Control for Chikungunya Disease",
                    author: "Miled ElHajji, PhD, Faculty of Science & Art",
                    sponsor: "قسم الرياضيات",
                    date: "31-03-2021",
                    poster: "Files/856/Galleries/7279/55991_semi9.jpg",
                    video: "https://jeddahu-my.sharepoint.com/:v:/g/personal/csa_math_kamil_uj_edu_sa/EUkPxSkvQTlFgKKQhjN4AhEBoZjDeKacNKt1GM4LFHBVNg?e=W5PECg",
                    url: "",
                },
                {
                    title: "Identification of Points Sources via Time Fractional Diffusion Equation",
                    author: "Ridha Mdimagh, PhD, Faculty of Science & Art (Khulais)",
                    sponsor: "قسم الرياضيات",
                    date: "14-04-2021",
                    poster: "",
                    video: "",
                    url: "",
                },
                {
                    title: "Modified Laplace Transform and Ordinary Differential Equations with Variable Coefficients",
                    author: "Prof. Tarig Alzaki, College of Sciences and Arts at Al Kamil-University of Jeddah",
                    date: "13-09-2021",
                    sponsor: "قسم الرياضيات",
                    poster: "",
                    video: "",
                    url: "",
                },
                {
                    title: "Optimal Porosity Designs for Gas Diffusion Layers of Hydrogen Fuel Cells",
                    author: "Dr. Jamal Hussain Al-Smail, Mathematics Department, (KFUPM)",
                    date: "27-09-2021",
                    sponsor: "قسم الرياضيات",
                    poster: "Files/856/Galleries/7279/55992_semi11.png",
                    video: "https://jeddahu-my.sharepoint.com/:v:/g/personal/csa_math_kamil_uj_edu_sa/ER_CbKigiKxBtl5kyqyvoT8B8w0hiNo6Q6lOvEsODNkymA?e=uCIM5X",
                    url: "",
                },
                {
                    title: "Nonexistence result for the generalized Tricomi equation with the scale-invariant damping, mass term and time derivative nonlinearity",
                    author: "Dr. Moahmed Fahmi Ben Hassen, Imam Abdulrahman Bin Faisal Uiversity",
                    date: "6-10-2021",
                    sponsor: "قسم الرياضيات",
                    poster: "Files/856/Galleries/7279/55993_semi12.png",
                    video: "https://jeddahu-my.sharepoint.com/:v:/g/personal/csa_math_kamil_uj_edu_sa/EdJm3sEaI59HjV83ATGv7IQBVAgYEIoltIYA7cZIHI8Taw?e=JmHImf",
                    url: "",
                },
                {
                    title: "How to write an effective scientific paper.",
                    author: "Prof. K. S. Nisar (Highly cited), College of Arts and science -Prince Sattam bin Abdulaziz University.",
                    date: "18-10-2021",
                    sponsor: "قسم الرياضيات",
                    poster: "Files/856/Galleries/7279/55994_semi13.png",
                    video: "https://jeddahu-my.sharepoint.com/:v:/g/personal/csa_math_kamil_uj_edu_sa/EdTh6d0uP7lOokSIvK-9w10B1qcXI2NNjPq4PjMHWGjeQw?e=WggWqc",
                    url: "",
                },
                {
                    title: "A conforming locking-free approximation for a Koiter shell",
                    author: "DR. Hanen Ferchichi, Jouf University",
                    date: "1-11-2021",
                    sponsor: "قسم الرياضيات",
                    poster: "Files/856/Galleries/7279/55995_semi14.jpg",
                    video: "https://jeddahu-my.sharepoint.com/:v:/g/personal/csa_math_kamil_uj_edu_sa/EeAuqe9XWbhBrL2MCXlNjqUBSZHmoWgDQTVkMBKEvD5rwQ?e=nPGfnP",
                    url: "",
                },
                {
                    title: "Point Source Identification Problem for a Time Fractional Diffusion Equation.",
                    author: "Prof. Imen Ben Saad Mdimagh, College of Sciences and ArtsatKheless -University of Jeddah",
                    date: "15-11-2021",
                    sponsor: "قسم الرياضيات",
                    poster: "Files/856/Galleries/7279/55996_semi15.jpg",
                    video: "https://jeddahu-my.sharepoint.com/:v:/g/personal/csa_math_kamil_uj_edu_sa/EW0tpBxDX5pOhBr3ZYHJ3E8BDh5TLvGQUL1wDDDCb6nkQA?e=wAgSxM",
                    url: "",
                },
                {
                    title: "Fractal Fractional Model of Drilling Nanoliquid with Clay Nanoparticles",
                    author: "Prof. Ilyas Khan (Highly cited), College of Engineering -Majmaah University",
                    date: "29-11-2021",
                    sponsor: "قسم الرياضيات",
                    poster: "Files/856/Galleries/7279/55997_semi16.jpg",
                    video: "https://jeddahu-my.sharepoint.com/:v:/g/personal/csa_math_kamil_uj_edu_sa/EWHNbINGYflBvrEmtBl3V5MBPYwntASurzvBOpKRSI5jzA?e=D5R3gz",
                    url: "",
                },
                {
                    title: "Numerical Solution of the Multiterm Time-Fractional Model for Heat Conductivity by Local Meshless Technique.",
                    author: "Majdi Alsolami, PhD, College of Sciences and Arts at Al Kamil-University of Jeddah",
                    date: "20-12-2021",
                    sponsor: "قسم الرياضيات",
                    poster: "",
                    video: "",
                    url: "",
                },
                ]
            },
            {
                year: "1443-1444",
                list: [
                    {
                        title: " Rapid Exponential Stabilization of Nonlinear Wave Equation Derived from Brain Activity via Event-Triggered Impulsive Control",
                        sponsor: "قسم الرياضيات",
                        author: " Dr. Mohsen Dlala, Mathematics department College of Science Qassim University",
                        date: " 31-01-2022",
                        poster: "",
                        video: "",
                        url: "",
                    },
                    {
                        title: " الملتقى الطلابي 5 لجامعة جدة",
                        author: "",
                        date: "6-02-2022",                        
                        sponsor: "قسم الرياضيات",
                        poster: "",
                        video: "",
                        url: "",
                    },
                    {
                        title: " Infinite Divisibility of Probability Measures and Special Functions",
                        sponsor: "قسم الرياضيات",
                        author: " Dr. Wissem Jdidi, King Saoud University",
                        date: " 14-02-2022",
                        poster: "",
                        video: "",
                        url: "",
                    },
                    {
                        title: " Mathematical and Numerical study of the concentration effect of red cells in blood",
                        sponsor: "قسم الرياضيات",
                        author: " Dr. Mourad Chamekh, College of Science and Arts Al Kamel University of Jeddah",
                        date: " 28-02-2022",
                        poster: "",
                        video: "",
                        url: "",
                    },
                    {
                        title: " Mathematical study for the phase-based transmissibility of a novel COVID-19 Coronavirus",
                        sponsor: "قسم الرياضيات",
                        author: " Dr. Miled El Hajji, College of Science University of Jeddah",
                        date: " 14-03-2022",
                        poster: "",
                        video: "",
                        url: "",
                    },
                    {
                        title: " Basics of academic writing for Higher education students",
                        sponsor: "قسم الرياضيات",
                        author: " Dr. Khaled Ouanes, Saudi Electronic University",
                        date: " 28-03-2022",
                        poster: "",
                        video: "",
                        url: "",
                    },
                    {
                        title: " Quasi Jawarneh Manifolds",
                        sponsor: "قسم الرياضيات",
                        author: " Dr. Moussa Jawarneh, College of Science and Arts Al Kamel University of Jeddah",
                        date: "11-04-2022 ",
                        poster: "",
                        video: "",
                        url: "",
                    },
                    {
                        title: " Dynamic spillovers effect and connectedness among climate change",
                        sponsor: "قسم الرياضيات",
                        author: " Dr. Rabeh Khalfaoui, College of Sciences and Humanities Shaqra University",
                        date: " 16-05-2022",
                        poster: "",
                        video: "",
                        url: "",
                    }
                ]
            },
      ]
  },
methods:{
  setYear: function (e) {
    this.selectedYear = eval(e.target.value)
  },
  showMoreInfo: function(item){
    this.modalData = item;
    const myModal = new bootstrap.Modal(document.querySelector('#moreInfo'))
    myModal.show();
    $('#video > video').get(0).load()
  }
},
created() {
  this.selectedYear = 0
},
});
